/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 58d3b355378e
 */

import { accessKeysDeleteByName } from "../funcs/access-keys-delete-by-name.js";
import { accessKeysDelete } from "../funcs/access-keys-delete.js";
import { accessKeysGenerate } from "../funcs/access-keys-generate.js";
import { accessKeysList } from "../funcs/access-keys-list.js";
import { accessKeysUpdate } from "../funcs/access-keys-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AccessKeys extends ClientSDK {
  /**
   * Get access keys
   *
   * @remarks
   * Retrieve an array of all access keys for a product environment.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#get_access_keys} - Learn more about retrieving access keys.
   */
  async list(
    request: models.GetAccessKeysRequest,
    options?: RequestOptions,
  ): Promise<models.AccessKeysResponse> {
    return unwrapAsync(accessKeysList(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate an access key
   *
   * @remarks
   * Generate a new access key.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#generate_an_access_key} - Learn more about generating access keys.
   */
  async generate(
    request: models.GenerateAccessKeyRequest,
    options?: RequestOptions,
  ): Promise<models.AccessKey> {
    return unwrapAsync(accessKeysGenerate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete access key by name
   *
   * @remarks
   * Delete a specific access key by name.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#delete_an_access_key} - Learn more about deleting access keys.
   */
  async deleteByName(
    request: models.DeleteAccessKeyByNameRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(accessKeysDeleteByName(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an access key
   *
   * @remarks
   * Update the name and/or status of an existing access key.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#update_an_access_key} - Learn more about updating access keys.
   */
  async update(
    request: models.UpdateAccessKeyRequest,
    options?: RequestOptions,
  ): Promise<models.AccessKey> {
    return unwrapAsync(accessKeysUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete access key
   *
   * @remarks
   * Delete a specific access key.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#delete_an_access_key} - Learn more about deleting access keys.
   */
  async delete(
    request: models.DeleteAccessKeyRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(accessKeysDelete(
      this,
      request,
      options,
    ));
  }
}
