/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { billingUsageGet } from "../funcs/billingUsageGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class BillingUsage extends ClientSDK {
  /**
   * Get billing usage information
   *
   * @remarks
   * Retrieve billing usage metrics for your account and product environments,
   * including storage, bandwidth, impressions, and transformations.
   *
   * If `year` is provided:
   *   - **Annual subscription**: Returns the single annual usage cycle that began in the specified year (if any).
   *   - **Monthly subscription**: Returns all monthly usage cycles that began in the specified year.
   *
   * If `year` is not provided:
   *   - Returns usage for the year in which the current active subscription period began.
   *   - If no active subscription exists, an empty list is returned.
   *
   * **Note**: Usage metrics are updated daily, so calling this endpoint once per day gives you the latest data.
   */
  async get(
    year?: number | undefined,
    includeProdenvBreakdown?: boolean | undefined,
    options?: RequestOptions,
  ): Promise<Array<models.BillingUsageResponse>> {
    return unwrapAsync(billingUsageGet(
      this,
      year,
      includeProdenvBreakdown,
      options,
    ));
  }
}
