/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e31c73b8e41c
 */

import { effectivePoliciesList } from "../funcs/effective-policies-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EffectivePolicies extends ClientSDK {
  /**
   * Get effective policies
   *
   * @remarks
   * Retrieve all roles (along with their system permission policies) associated with principals, and all custom permission policies directly added to principals, all within a specified scope.
   *
   * Optionally specify a principal to only include roles and policies associated with that principal.
   */
  async list(
    request?: models.GetEffectivePoliciesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.EffectivePoliciesResponse> {
    return unwrapAsync(effectivePoliciesList(
      this,
      request,
      options,
    ));
  }
}
