/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { effectivePoliciesList } from "../funcs/effectivePoliciesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class EffectivePolicies extends ClientSDK {
  /**
   * Get effective policies
   *
   * @remarks
   * Retrieve all roles (along with their system permission policies) associated with principals, and all custom permission policies directly added to principals, all within a specified scope.
   *
   * Optionally specify a principal to only include roles and policies associated with that principal.
   */
  async list(
    scopeType?: models.ScopeTypeEnum | undefined,
    scopeId?: string | undefined,
    principalType?: models.PrincipalTypeEnum | undefined,
    principalId?: string | undefined,
    options?: RequestOptions,
  ): Promise<models.EffectivePoliciesResponse> {
    return unwrapAsync(effectivePoliciesList(
      this,
      scopeType,
      scopeId,
      principalType,
      principalId,
      options,
    ));
  }
}
