/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { principalsInspectMultiple } from "../funcs/principals-inspect-multiple.js";
import { principalsInspect } from "../funcs/principals-inspect.js";
import { principalsListRoles } from "../funcs/principals-list-roles.js";
import { principalsUpdateRoles } from "../funcs/principals-update-roles.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Principals extends ClientSDK {
  /**
   * Get a principal's roles
   *
   * @remarks
   * Retrieve all roles associated with a specific principal.
   */
  async listRoles(
    request: models.GetPrincipalRolesRequest,
    options?: RequestOptions,
  ): Promise<models.PrincipalRolesResponse> {
    return unwrapAsync(principalsListRoles(
      this,
      request,
      options,
    ));
  }

  /**
   * Assign roles to a principal
   *
   * @remarks
   * Add or remove roles associated with a principal.
   */
  async updateRoles(
    request: models.UpdatePrincipalRolesRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(principalsUpdateRoles(
      this,
      request,
      options,
    ));
  }

  /**
   * Inspect
   *
   * @remarks
   * Retrieves principals and their assigned roles within a specified scope, based on query filters.
   *
   * Use this endpoint to determine which users, groups, API keys, or account API keys have roles applied at:
   * * A specific `scope_type` ("account" or "prodenv")
   * * A specific `scope_id` (for product environments)
   * * Optional content filters (such as `folder_id`, `collection_id`, or `param_key` / `param_value`)
   * * Optional `principal_type` (and `principal_id`)
   *
   * The response includes all principals that match the specified filters, along with the roles applied to them within that context.
   *
   * This endpoint is useful when you want to:
   * * Audit who has access within a given scope
   * * Identify all principals assigned to roles for a specific folder, collection, asset, or product environment
   * * Retrieve role assignments dynamically based on filtering criteria
   */
  async inspect(
    request: models.InspectRequest1,
    options?: RequestOptions,
  ): Promise<models.PrincipalRolesInspectResponse> {
    return unwrapAsync(principalsInspect(
      this,
      request,
      options,
    ));
  }

  /**
   * Inspect multiple
   *
   * @remarks
   * Retrieves role assignments for a specified list of principals within a shared scope and optional policy parameters.
   *
   * Use this endpoint when you already know which principals you want to evaluate and want to check their role assignments in a single request.
   *
   * In this request:
   * * You explicitly provide the `principals` array in the request body.
   * * All principals are evaluated against the same `scope_type`, optional `scope_id`, and optional `policy_parameters`.
   * * Unlike `Inspect`, this endpoint doesn't search for matching principals. It evaluates only the principals you provide.
   *
   * This endpoint is useful for:
   * * Verify role assignments for multiple specified principals at once
   * * Comparing role assignments across specific users, groups, or keys
   * * Reducing multiple per-principal `Inspect` calls into a single request
   */
  async inspectMultiple(
    request: models.InspectRequest,
    options?: RequestOptions,
  ): Promise<models.PrincipalRolesInspectResponse> {
    return unwrapAsync(principalsInspectMultiple(
      this,
      request,
      options,
    ));
  }
}
