/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: e6128f1da3f6
 */

import { productEnvironmentsCreate } from "../funcs/product-environments-create.js";
import { productEnvironmentsDelete } from "../funcs/product-environments-delete.js";
import { productEnvironmentsGet } from "../funcs/product-environments-get.js";
import { productEnvironmentsList } from "../funcs/product-environments-list.js";
import { productEnvironmentsUpdate } from "../funcs/product-environments-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ProductEnvironments extends ClientSDK {
  /**
   * Get product environments
   *
   * @remarks
   * Return an array of all product environments, or if conditions are specified,
   * return the relevant product environments.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#get_product_environments} - Learn more about getting product environments.
   */
  async list(
    request?: models.GetProductEnvironmentsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.ProductEnvironmentsResponse> {
    return unwrapAsync(productEnvironmentsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create product environment
   *
   * @remarks
   * Create a new product environment. Any users that have access to all product environments will also automatically
   * have access to the new product environment.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#create_product_environment} - Learn more about creating product environments.
   */
  async create(
    request: models.ProductEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.ProductEnvironment> {
    return unwrapAsync(productEnvironmentsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get product environment
   *
   * @remarks
   * Retrieve a specific product environment.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#get_product_environment} - Learn more about retrieving specific product environments.
   */
  async get(
    request: models.GetProductEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.ProductEnvironment> {
    return unwrapAsync(productEnvironmentsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update product environment
   *
   * @remarks
   * Update the details of a product environment.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#update_product_environment} - Learn more about updating product environments.
   */
  async update(
    request: models.UpdateProductEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.ProductEnvironment> {
    return unwrapAsync(productEnvironmentsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete product environment
   *
   * @remarks
   * Delete a specific product environment.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#delete_product_environment} - Learn more about deleting product environments.
   */
  async delete(
    request: models.DeleteProductEnvironmentRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(productEnvironmentsDelete(
      this,
      request,
      options,
    ));
  }
}
