/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicGetCatalog } from "../funcs/public-get-catalog.js";
import { publicGetSchema } from "../funcs/public-get-schema.js";
import { publicValidatePolicy } from "../funcs/public-validate-policy.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Public extends ClientSDK {
  /**
   * Get system roles and policies catalog
   *
   * @remarks
   * Retrieves the catalog of predefined system roles and their associated policies.
   */
  async getCatalog(
    options?: RequestOptions,
  ): Promise<models.SystemRolesAndPoliciesCatalogResponse> {
    return unwrapAsync(publicGetCatalog(
      this,
      options,
    ));
  }

  /**
   * Validate a Cedar policy
   *
   * @remarks
   * Validate a Cedar policy
   */
  async validatePolicy(
    request: models.ValidateCedarPolicyRequest,
    options?: RequestOptions,
  ): Promise<models.ValidateCedarPolicyResponse> {
    return unwrapAsync(publicValidatePolicy(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Cedar schema
   *
   * @remarks
   * Get Cedar schema
   */
  async getSchema(
    options?: RequestOptions,
  ): Promise<models.CedarSchemaResponse> {
    return unwrapAsync(publicGetSchema(
      this,
      options,
    ));
  }
}
