/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rolesCreate } from "../funcs/rolesCreate.js";
import { rolesDelete } from "../funcs/rolesDelete.js";
import { rolesGet } from "../funcs/rolesGet.js";
import { rolesList } from "../funcs/rolesList.js";
import { rolesListPrincipals } from "../funcs/rolesListPrincipals.js";
import { rolesUpdate } from "../funcs/rolesUpdate.js";
import { rolesUpdatePrincipals } from "../funcs/rolesUpdatePrincipals.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Roles extends ClientSDK {
  /**
   * Get roles
   *
   * @remarks
   * Retrieve all system and custom roles of a specific `permission_type` (global or content-specific). Optionally filter by `scope_type`, `management_type`, and `policy_parameters`.
   */
  async list(
    permissionType: models.PermissionTypeEnum,
    scopeType?: models.ScopeTypeEnum | undefined,
    managementType?: models.ManagementTypeEnum | undefined,
    policyParameters?: Array<string> | undefined,
    options?: RequestOptions,
  ): Promise<models.RolesResponse> {
    return unwrapAsync(rolesList(
      this,
      permissionType,
      scopeType,
      managementType,
      policyParameters,
      options,
    ));
  }

  /**
   * Create custom role
   *
   * @remarks
   * Create a new custom role.
   */
  async create(
    request: models.CreateRole,
    options?: RequestOptions,
  ): Promise<models.RoleResponse> {
    return unwrapAsync(rolesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get role
   *
   * @remarks
   * Get a specific system or custom role.
   */
  async get(
    request: models.GetRoleRequest,
    options?: RequestOptions,
  ): Promise<models.RoleResponse> {
    return unwrapAsync(rolesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update custom role
   *
   * @remarks
   * Update a specific custom role by providing all relevant details, including those you want to keep as-is.
   *
   * *Note:* Updating a role with a name that already exists will trigger a 409 error.
   */
  async update(
    roleId: string,
    role: models.Role,
    options?: RequestOptions,
  ): Promise<models.RoleResponse> {
    return unwrapAsync(rolesUpdate(
      this,
      roleId,
      role,
      options,
    ));
  }

  /**
   * Delete custom role
   *
   * @remarks
   * Delete a specific custom role.
   */
  async delete(
    roleId: string,
    force?: boolean | undefined,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(rolesDelete(
      this,
      roleId,
      force,
      options,
    ));
  }

  /**
   * Get a role's principals
   *
   * @remarks
   * Retrieve all principals associated with a specific role.
   */
  async listPrincipals(
    request: models.GetRolePrincipalsRequest,
    options?: RequestOptions,
  ): Promise<models.PrincipalsResponse> {
    return unwrapAsync(rolesListPrincipals(
      this,
      request,
      options,
    ));
  }

  /**
   * Assign principals to a role
   *
   * @remarks
   * Add or remove principals associated with a role.
   */
  async updatePrincipals(
    roleId: string,
    updateRolePrincipalsRequest: models.UpdateRolePrincipalsRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(rolesUpdatePrincipals(
      this,
      roleId,
      updateRolePrincipalsRequest,
      options,
    ));
  }
}
