/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { AccessKeys } from "./accesskeys.js";
import { BillingUsage } from "./billingusage.js";
import { CustomPolicies } from "./custompolicies.js";
import { EffectivePolicies } from "./effectivepolicies.js";
import { Principals } from "./principals.js";
import { ProductEnvironments } from "./productenvironments.js";
import { Public } from "./public.js";
import { Roles } from "./roles.js";
import { SystemPolicies } from "./systempolicies.js";
import { UserGroups } from "./usergroups.js";
import { Users } from "./users.js";

export class CldProvisioning extends ClientSDK {
  private _productEnvironments?: ProductEnvironments;
  get productEnvironments(): ProductEnvironments {
    return (this._productEnvironments ??= new ProductEnvironments(
      this._options,
    ));
  }

  private _accessKeys?: AccessKeys;
  get accessKeys(): AccessKeys {
    return (this._accessKeys ??= new AccessKeys(this._options));
  }

  private _users?: Users;
  get users(): Users {
    return (this._users ??= new Users(this._options));
  }

  private _userGroups?: UserGroups;
  get userGroups(): UserGroups {
    return (this._userGroups ??= new UserGroups(this._options));
  }

  private _billingUsage?: BillingUsage;
  get billingUsage(): BillingUsage {
    return (this._billingUsage ??= new BillingUsage(this._options));
  }

  private _public?: Public;
  get public(): Public {
    return (this._public ??= new Public(this._options));
  }

  private _systemPolicies?: SystemPolicies;
  get systemPolicies(): SystemPolicies {
    return (this._systemPolicies ??= new SystemPolicies(this._options));
  }

  private _customPolicies?: CustomPolicies;
  get customPolicies(): CustomPolicies {
    return (this._customPolicies ??= new CustomPolicies(this._options));
  }

  private _effectivePolicies?: EffectivePolicies;
  get effectivePolicies(): EffectivePolicies {
    return (this._effectivePolicies ??= new EffectivePolicies(this._options));
  }

  private _roles?: Roles;
  get roles(): Roles {
    return (this._roles ??= new Roles(this._options));
  }

  private _principals?: Principals;
  get principals(): Principals {
    return (this._principals ??= new Principals(this._options));
  }
}
