/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { systemPoliciesList } from "../funcs/system-policies-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class SystemPolicies extends ClientSDK {
  /**
   * Get system policies
   *
   * @remarks
   * Retrieve all system-defined permission policies. Optionally filter the results by `scope_type` (account or product environment) and/or `permission_type` (global or content-specific).
   *
   * **Note:** If `scope_type` isn't specified as `prodenv`, the account-level policies will be returned.
   */
  async list(
    request?: models.GetSystemPoliciesRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.SystemPoliciesResponse> {
    return unwrapAsync(systemPoliciesList(
      this,
      request,
      options,
    ));
  }
}
