/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGroupsAddUser } from "../funcs/user-groups-add-user.js";
import { userGroupsCreate } from "../funcs/user-groups-create.js";
import { userGroupsDelete } from "../funcs/user-groups-delete.js";
import { userGroupsGet } from "../funcs/user-groups-get.js";
import { userGroupsListUsers } from "../funcs/user-groups-list-users.js";
import { userGroupsList } from "../funcs/user-groups-list.js";
import { userGroupsRemoveUser } from "../funcs/user-groups-remove-user.js";
import { userGroupsUpdate } from "../funcs/user-groups-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class UserGroups extends ClientSDK {
  /**
   * Get User Groups
   *
   * @remarks
   * Retrieve an array of all user groups in the account.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#get_user_groups} - Learn more about retrieving user groups.
   */
  async list(
    request?: models.GetUserGroupsRequest | undefined,
    options?: RequestOptions,
  ): Promise<models.UserGroupsResponse> {
    return unwrapAsync(userGroupsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create User Group
   *
   * @remarks
   * Create a new user group for the account.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#create_user_group} - Learn more about creating user groups.
   */
  async create(
    request: models.UserGroupRequest,
    options?: RequestOptions,
  ): Promise<models.UserGroup> {
    return unwrapAsync(userGroupsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get User Group
   *
   * @remarks
   * Retrieve a specific user group.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#get_user_group} - Learn more about retrieving a specific user group.
   */
  async get(
    request: models.GetUserGroupRequest,
    options?: RequestOptions,
  ): Promise<models.UserGroup> {
    return unwrapAsync(userGroupsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update User Group
   *
   * @remarks
   * Update the name of a specified user group.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#update_user_group} - Learn more about updating a specific user group.
   */
  async update(
    request: models.UpdateUserGroupRequest,
    options?: RequestOptions,
  ): Promise<models.UserGroup> {
    return unwrapAsync(userGroupsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete User Group
   *
   * @remarks
   * Delete a user group with the specified ID.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#delete_user_group} - Learn more about deleting a specific user group.
   */
  async delete(
    request: models.DeleteUserGroupRequest,
    options?: RequestOptions,
  ): Promise<models.SuccessResponse> {
    return unwrapAsync(userGroupsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Users in User Group
   *
   * @remarks
   * Retrieve the users in the group with the specified ID.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#get_user_group_users} - Learn more about retrieving users in a specific user group.
   */
  async listUsers(
    request: models.GetUsersInUserGroupRequest,
    options?: RequestOptions,
  ): Promise<models.UserGroupUsersResponse> {
    return unwrapAsync(userGroupsListUsers(
      this,
      request,
      options,
    ));
  }

  /**
   * Add User to User Group
   *
   * @remarks
   * Add a user to a group with the specified ID.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#add_user_to_group} - Learn more about adding users to a specific user group.
   */
  async addUser(
    request: models.AddUserToUserGroupRequest,
    options?: RequestOptions,
  ): Promise<models.UserGroupUser> {
    return unwrapAsync(userGroupsAddUser(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove User from User Group
   *
   * @remarks
   * Remove a user from a group with the specified ID.
   *
   * @see {@link https://cloudinary.com/documentation/provisioning_api#remove_user_from_group} - Learn more about removing users from a specific user group.
   */
  async removeUser(
    request: models.RemoveUserFromUserGroupRequest,
    options?: RequestOptions,
  ): Promise<models.UserGroupUsersResponse> {
    return unwrapAsync(userGroupsRemoveUser(
      this,
      request,
      options,
    ));
  }
}
