/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @cloudinary/account-provisioning SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx productEnvironmentsList.example.ts
 */

import { CldProvisioning } from "@cloudinary/account-provisioning";

const cldProvisioning = new CldProvisioning({
  accountId: "<id>",
  security: {
    provisioningApiKey: "CLOUDINARY_PROVISIONING_API_KEY",
    provisioningApiSecret: "CLOUDINARY_PROVISIONING_API_SECRET",
  },
});

async function main() {
  const result = await cldProvisioning.productEnvironments.list(
    true,
    undefined,
    undefined,
    "product",
  );

  console.log(result);
}

main().catch(console.error);
