/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AccessKeyRequest = {
  /**
   * The name of the access key.
   */
  name?: string | undefined;
  /**
   * Whether the access key is enabled or disabled.
   */
  enabled?: boolean | undefined;
};

/** @internal */
export type AccessKeyRequest$Outbound = {
  name?: string | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const AccessKeyRequest$outboundSchema: z.ZodType<
  AccessKeyRequest$Outbound,
  z.ZodTypeDef,
  AccessKeyRequest
> = z.object({
  name: z.string().optional(),
  enabled: z.boolean().optional(),
});

export function accessKeyRequestToJSON(
  accessKeyRequest: AccessKeyRequest,
): string {
  return JSON.stringify(
    AccessKeyRequest$outboundSchema.parse(accessKeyRequest),
  );
}
