/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type AccessKey = {
  /**
   * The name of the access key.
   */
  name?: string | undefined;
  /**
   * The API key.
   */
  apiKey?: string | undefined;
  /**
   * The API secret.
   */
  apiSecret?: string | undefined;
  /**
   * The date when the access key was created.
   */
  createdAt?: Date | undefined;
  /**
   * The date when the access key was last updated.
   */
  updatedAt?: Date | undefined;
  /**
   * Whether the access key is enabled or disabled.
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const AccessKey$inboundSchema: z.ZodType<
  AccessKey,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  api_key: z.string().optional(),
  api_secret: z.string().optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  enabled: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "api_key": "apiKey",
    "api_secret": "apiSecret",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function accessKeyFromJSON(
  jsonString: string,
): SafeParseResult<AccessKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccessKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccessKey' from JSON`,
  );
}
