/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 49c90333c868
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * Designates the access key for a specific purpose while allowing it to be used for other purposes, as well.
 *
 * @remarks
 * This action replaces any previously assigned key. **Possible values**: `webhooks`
 */
export const DedicatedFor = {
  Webhooks: "webhooks",
} as const;
/**
 * Designates the access key for a specific purpose while allowing it to be used for other purposes, as well.
 *
 * @remarks
 * This action replaces any previously assigned key. **Possible values**: `webhooks`
 */
export type DedicatedFor = ClosedEnum<typeof DedicatedFor>;

export type AccessKeyUpdateRequest = {
  /**
   * The name of the access key.
   */
  name?: string | undefined;
  /**
   * Whether the access key is enabled or disabled.
   */
  enabled?: boolean | undefined;
  /**
   * Designates the access key for a specific purpose while allowing it to be used for other purposes, as well.
   *
   * @remarks
   * This action replaces any previously assigned key. **Possible values**: `webhooks`
   */
  dedicatedFor?: DedicatedFor | undefined;
};

/** @internal */
export const DedicatedFor$outboundSchema: z.ZodMiniEnum<typeof DedicatedFor> = z
  .enum(DedicatedFor);

/** @internal */
export type AccessKeyUpdateRequest$Outbound = {
  name?: string | undefined;
  enabled?: boolean | undefined;
  dedicated_for?: string | undefined;
};

/** @internal */
export const AccessKeyUpdateRequest$outboundSchema: z.ZodMiniType<
  AccessKeyUpdateRequest$Outbound,
  AccessKeyUpdateRequest
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    enabled: z.optional(z.boolean()),
    dedicatedFor: z.optional(DedicatedFor$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      dedicatedFor: "dedicated_for",
    });
  }),
);

export function accessKeyUpdateRequestToJSON(
  accessKeyUpdateRequest: AccessKeyUpdateRequest,
): string {
  return JSON.stringify(
    AccessKeyUpdateRequest$outboundSchema.parse(accessKeyUpdateRequest),
  );
}
