/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a510acebef2b
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * Brief details of a single API Access Key.
 */
export type ApiAccessKey = {
  /**
   * The API key.
   */
  key?: string | undefined;
  /**
   * The API secret.
   */
  secret?: string | undefined;
  /**
   * Whether the access key is enabled or disabled.
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const ApiAccessKey$inboundSchema: z.ZodMiniType<ApiAccessKey, unknown> =
  z.object({
    key: types.optional(types.string()),
    secret: types.optional(types.string()),
    enabled: types.optional(types.boolean()),
  });

export function apiAccessKeyFromJSON(
  jsonString: string,
): SafeParseResult<ApiAccessKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiAccessKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiAccessKey' from JSON`,
  );
}
