/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * Brief details of a single API Access Key.
 */
export type ApiAccessKey = {
  /**
   * The API key.
   */
  key?: string | undefined;
  /**
   * The API secret.
   */
  secret?: string | undefined;
  /**
   * Whether the access key is enabled or disabled.
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const ApiAccessKey$inboundSchema: z.ZodType<
  ApiAccessKey,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string().optional(),
  secret: z.string().optional(),
  enabled: z.boolean().optional(),
});

export function apiAccessKeyFromJSON(
  jsonString: string,
): SafeParseResult<ApiAccessKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiAccessKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiAccessKey' from JSON`,
  );
}
