/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  CloudAssetTypeBreakdown,
  CloudAssetTypeBreakdown$inboundSchema,
} from "./cloud-asset-type-breakdown.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * Usage breakdown by asset type and operation.
 */
export type Breakdown = {
  /**
   * Storage usage for images.
   */
  storageImage?: number | undefined;
  /**
   * Storage usage for videos.
   */
  storageVideo?: number | undefined;
  /**
   * Storage usage for raw files.
   */
  storageRaw?: number | undefined;
  /**
   * Transformation usage for images.
   */
  transformationsImage?: number | undefined;
  /**
   * Transformation usage for videos.
   */
  transformationsVideo?: number | undefined;
  /**
   * Bandwidth usage for images.
   */
  bandwidthImage?: number | undefined;
  /**
   * Bandwidth usage for videos.
   */
  bandwidthVideo?: number | undefined;
  /**
   * Bandwidth usage for raw files.
   */
  bandwidthRaw?: number | undefined;
  /**
   * Number of times images were delivered (impressions).
   */
  imageImpressions?: number | undefined;
  /**
   * Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio).
   */
  videoSeconds?: number | undefined;
};

export type Cycles = {
  /**
   * The start date of the billing cycle.
   */
  fromDay?: Date | undefined;
  /**
   * The end date of the billing cycle.
   */
  toDay?: Date | undefined;
  /**
   * Total usage for this cycle.
   */
  usage?: number | undefined;
  /**
   * Usage breakdown by asset type and operation.
   */
  breakdown?: Breakdown | undefined;
  /**
   * Optional breakdown by product environment. May not be present in all responses.
   */
  productEnvironmentBreakdown?: Array<CloudAssetTypeBreakdown> | undefined;
};

/**
 * Usage breakdown by asset type and operation for the monthly cycle.
 */
export type BillingUsageResponseBreakdown = {
  /**
   * Storage usage for images.
   */
  storageImage?: number | undefined;
  /**
   * Storage usage for videos.
   */
  storageVideo?: number | undefined;
  /**
   * Storage usage for raw files.
   */
  storageRaw?: number | undefined;
  /**
   * Transformation usage for images.
   */
  transformationsImage?: number | undefined;
  /**
   * Transformation usage for videos.
   */
  transformationsVideo?: number | undefined;
  /**
   * Bandwidth usage for images.
   */
  bandwidthImage?: number | undefined;
  /**
   * Bandwidth usage for videos.
   */
  bandwidthVideo?: number | undefined;
  /**
   * Bandwidth usage for raw files.
   */
  bandwidthRaw?: number | undefined;
  /**
   * Number of times images were delivered (impressions).
   */
  imageImpressions?: number | undefined;
  /**
   * Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio).
   */
  videoSeconds?: number | undefined;
};

export type MonthlyCycles = {
  /**
   * The start date of the monthly billing cycle.
   */
  fromDay?: Date | undefined;
  /**
   * The end date of the monthly billing cycle.
   */
  toDay?: Date | undefined;
  /**
   * Total usage for this monthly cycle.
   */
  usage?: number | undefined;
  /**
   * Usage breakdown by asset type and operation for the monthly cycle.
   */
  breakdown?: BillingUsageResponseBreakdown | undefined;
  /**
   * Optional breakdown by product environment for the monthly cycle. May not be present in all responses.
   */
  productEnvironmentBreakdown?: Array<CloudAssetTypeBreakdown> | undefined;
};

export type MetricUsage = {
  /**
   * The type of metric being measured (e.g., "credit").
   */
  metric?: string | undefined;
  /**
   * The limit for this metric in the plan.
   */
  limit?: number | undefined;
  /**
   * Full usage details per billing cycle (monthly or annual, depending on plan).
   */
  cycles?: Array<Cycles> | undefined;
  /**
   * Monthly-level breakdown within a single annual cycle.
   */
  monthlyCycles?: Array<MonthlyCycles> | undefined;
};

export type BillingUsageResponse = {
  /**
   * The name of the plan (e.g., "Pro PAYG", "Advanced PAYG").
   */
  planName?: string | undefined;
  metricUsage?: Array<MetricUsage> | undefined;
};

/** @internal */
export const Breakdown$inboundSchema: z.ZodMiniType<Breakdown, unknown> = z
  .pipe(
    z.object({
      storage_image: types.optional(types.number()),
      storage_video: types.optional(types.number()),
      storage_raw: types.optional(types.number()),
      transformations_image: types.optional(types.number()),
      transformations_video: types.optional(types.number()),
      bandwidth_image: types.optional(types.number()),
      bandwidth_video: types.optional(types.number()),
      bandwidth_raw: types.optional(types.number()),
      image_impressions: types.optional(types.number()),
      video_seconds: types.optional(types.number()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "storage_image": "storageImage",
        "storage_video": "storageVideo",
        "storage_raw": "storageRaw",
        "transformations_image": "transformationsImage",
        "transformations_video": "transformationsVideo",
        "bandwidth_image": "bandwidthImage",
        "bandwidth_video": "bandwidthVideo",
        "bandwidth_raw": "bandwidthRaw",
        "image_impressions": "imageImpressions",
        "video_seconds": "videoSeconds",
      });
    }),
  );

export function breakdownFromJSON(
  jsonString: string,
): SafeParseResult<Breakdown, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Breakdown$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Breakdown' from JSON`,
  );
}

/** @internal */
export const Cycles$inboundSchema: z.ZodMiniType<Cycles, unknown> = z.pipe(
  z.object({
    from_day: types.optional(types.date()),
    to_day: types.optional(types.date()),
    usage: types.optional(types.number()),
    breakdown: types.optional(z.lazy(() => Breakdown$inboundSchema)),
    product_environment_breakdown: types.optional(
      z.array(CloudAssetTypeBreakdown$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "from_day": "fromDay",
      "to_day": "toDay",
      "product_environment_breakdown": "productEnvironmentBreakdown",
    });
  }),
);

export function cyclesFromJSON(
  jsonString: string,
): SafeParseResult<Cycles, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Cycles$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Cycles' from JSON`,
  );
}

/** @internal */
export const BillingUsageResponseBreakdown$inboundSchema: z.ZodMiniType<
  BillingUsageResponseBreakdown,
  unknown
> = z.pipe(
  z.object({
    storage_image: types.optional(types.number()),
    storage_video: types.optional(types.number()),
    storage_raw: types.optional(types.number()),
    transformations_image: types.optional(types.number()),
    transformations_video: types.optional(types.number()),
    bandwidth_image: types.optional(types.number()),
    bandwidth_video: types.optional(types.number()),
    bandwidth_raw: types.optional(types.number()),
    image_impressions: types.optional(types.number()),
    video_seconds: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "storage_image": "storageImage",
      "storage_video": "storageVideo",
      "storage_raw": "storageRaw",
      "transformations_image": "transformationsImage",
      "transformations_video": "transformationsVideo",
      "bandwidth_image": "bandwidthImage",
      "bandwidth_video": "bandwidthVideo",
      "bandwidth_raw": "bandwidthRaw",
      "image_impressions": "imageImpressions",
      "video_seconds": "videoSeconds",
    });
  }),
);

export function billingUsageResponseBreakdownFromJSON(
  jsonString: string,
): SafeParseResult<BillingUsageResponseBreakdown, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingUsageResponseBreakdown$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingUsageResponseBreakdown' from JSON`,
  );
}

/** @internal */
export const MonthlyCycles$inboundSchema: z.ZodMiniType<
  MonthlyCycles,
  unknown
> = z.pipe(
  z.object({
    from_day: types.optional(types.date()),
    to_day: types.optional(types.date()),
    usage: types.optional(types.number()),
    breakdown: types.optional(
      z.lazy(() => BillingUsageResponseBreakdown$inboundSchema),
    ),
    product_environment_breakdown: types.optional(
      z.array(CloudAssetTypeBreakdown$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "from_day": "fromDay",
      "to_day": "toDay",
      "product_environment_breakdown": "productEnvironmentBreakdown",
    });
  }),
);

export function monthlyCyclesFromJSON(
  jsonString: string,
): SafeParseResult<MonthlyCycles, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MonthlyCycles$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MonthlyCycles' from JSON`,
  );
}

/** @internal */
export const MetricUsage$inboundSchema: z.ZodMiniType<MetricUsage, unknown> = z
  .pipe(
    z.object({
      metric: types.optional(types.string()),
      limit: types.optional(types.number()),
      cycles: types.optional(z.array(z.lazy(() => Cycles$inboundSchema))),
      monthly_cycles: types.optional(
        z.array(z.lazy(() => MonthlyCycles$inboundSchema)),
      ),
    }),
    z.transform((v) => {
      return remap$(v, {
        "monthly_cycles": "monthlyCycles",
      });
    }),
  );

export function metricUsageFromJSON(
  jsonString: string,
): SafeParseResult<MetricUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MetricUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MetricUsage' from JSON`,
  );
}

/** @internal */
export const BillingUsageResponse$inboundSchema: z.ZodMiniType<
  BillingUsageResponse,
  unknown
> = z.pipe(
  z.object({
    plan_name: types.optional(types.string()),
    metric_usage: types.optional(
      z.array(z.lazy(() => MetricUsage$inboundSchema)),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "plan_name": "planName",
      "metric_usage": "metricUsage",
    });
  }),
);

export function billingUsageResponseFromJSON(
  jsonString: string,
): SafeParseResult<BillingUsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BillingUsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BillingUsageResponse' from JSON`,
  );
}
