/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type CedarError = {
  cedarMessage: string;
  cedarCode: string;
};

/** @internal */
export const CedarError$inboundSchema: z.ZodMiniType<CedarError, unknown> = z
  .pipe(
    z.object({
      cedar_message: types.string(),
      cedar_code: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "cedar_message": "cedarMessage",
        "cedar_code": "cedarCode",
      });
    }),
  );

export function cedarErrorFromJSON(
  jsonString: string,
): SafeParseResult<CedarError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CedarError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CedarError' from JSON`,
  );
}
