/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type Schema = {};

export type CedarSchemaResponse = {
  schema: Schema;
};

/** @internal */
export const Schema$inboundSchema: z.ZodType<Schema, z.ZodTypeDef, unknown> = z
  .object({});

export function schemaFromJSON(
  jsonString: string,
): SafeParseResult<Schema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Schema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Schema' from JSON`,
  );
}

/** @internal */
export const CedarSchemaResponse$inboundSchema: z.ZodType<
  CedarSchemaResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  schema: z.lazy(() => Schema$inboundSchema),
});

export function cedarSchemaResponseFromJSON(
  jsonString: string,
): SafeParseResult<CedarSchemaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CedarSchemaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CedarSchemaResponse' from JSON`,
  );
}
