/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type CedarError = {
  cedarMessage: string;
  cedarCode: string;
};

/** @internal */
export const CedarError$inboundSchema: z.ZodType<
  CedarError,
  z.ZodTypeDef,
  unknown
> = z.object({
  cedar_message: z.string(),
  cedar_code: z.string(),
}).transform((v) => {
  return remap$(v, {
    "cedar_message": "cedarMessage",
    "cedar_code": "cedarCode",
  });
});

export function cedarErrorFromJSON(
  jsonString: string,
): SafeParseResult<CedarError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CedarError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CedarError' from JSON`,
  );
}
