/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type CloudAssetTypeBreakdown = {
  /**
   * Storage usage for images in this product environment.
   */
  storageImage?: number | undefined;
  /**
   * Storage usage for videos in this product environment.
   */
  storageVideo?: number | undefined;
  /**
   * Storage usage for raw files in this product environment.
   */
  storageRaw?: number | undefined;
  /**
   * Transformation usage for images in this product environment.
   */
  transformationsImage?: number | undefined;
  /**
   * Transformation usage for videos in this product environment.
   */
  transformationsVideo?: number | undefined;
  /**
   * Bandwidth usage for images in this product environment.
   */
  bandwidthImage?: number | undefined;
  /**
   * Bandwidth usage for videos in this product environment.
   */
  bandwidthVideo?: number | undefined;
  /**
   * Bandwidth usage for raw files in this product environment.
   */
  bandwidthRaw?: number | undefined;
  /**
   * Number of times images were delivered (impressions) in this product environment.
   */
  imageImpressions?: number | undefined;
  /**
   * Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio).
   */
  videoSeconds?: number | undefined;
  /**
   * The name of the product environment.
   */
  cloudName?: string | undefined;
};

/** @internal */
export const CloudAssetTypeBreakdown$inboundSchema: z.ZodType<
  CloudAssetTypeBreakdown,
  z.ZodTypeDef,
  unknown
> = z.object({
  storage_image: z.number().optional(),
  storage_video: z.number().optional(),
  storage_raw: z.number().optional(),
  transformations_image: z.number().optional(),
  transformations_video: z.number().optional(),
  bandwidth_image: z.number().optional(),
  bandwidth_video: z.number().optional(),
  bandwidth_raw: z.number().optional(),
  image_impressions: z.number().optional(),
  video_seconds: z.number().optional(),
  cloud_name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "storage_image": "storageImage",
    "storage_video": "storageVideo",
    "storage_raw": "storageRaw",
    "transformations_image": "transformationsImage",
    "transformations_video": "transformationsVideo",
    "bandwidth_image": "bandwidthImage",
    "bandwidth_video": "bandwidthVideo",
    "bandwidth_raw": "bandwidthRaw",
    "image_impressions": "imageImpressions",
    "video_seconds": "videoSeconds",
    "cloud_name": "cloudName",
  });
});

export function cloudAssetTypeBreakdownFromJSON(
  jsonString: string,
): SafeParseResult<CloudAssetTypeBreakdown, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CloudAssetTypeBreakdown$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CloudAssetTypeBreakdown' from JSON`,
  );
}
