/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4592b9b18bb2
 */

export type CreateCustomPolicyGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};
