/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$outboundSchema,
} from "./scopetypeenum.js";

export type CreateRole = {
  /**
   * The unique identifier for the role.
   *
   * @remarks
   *
   * * **When creating a new role**: If not provided, the system will auto-generate the ID.
   * * **When updating a role**: Specify the ID of the role you want to update.
   */
  id?: string | undefined;
  /**
   * Specifies whether the permission applies globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID `"fg3841spr"`). **Note:** This attrubute is immutable.
   *
   * @remarks
   * - global
   * - content
   */
  permissionType: string;
  /**
   * Specifies where the role/policy is applied, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  /**
   * The name of the role.
   */
  name: string;
  /**
   * A short description of the role.
   */
  description?: string | null | undefined;
  /**
   * A list of system permission policy IDs to be included in the role.
   *
   * @remarks
   *
   * **Tip:** Get the list of all available predefined policies using the [Get system policies](#tag/policies/get/policies) method.
   */
  systemPolicyIds?: Array<string> | undefined;
};

/** @internal */
export type CreateRole$Outbound = {
  id?: string | undefined;
  permission_type: string;
  scope_type: string;
  name: string;
  description?: string | null | undefined;
  system_policy_ids?: Array<string> | undefined;
};

/** @internal */
export const CreateRole$outboundSchema: z.ZodType<
  CreateRole$Outbound,
  z.ZodTypeDef,
  CreateRole
> = z.object({
  id: z.string().optional(),
  permissionType: z.string(),
  scopeType: ScopeTypeEnum$outboundSchema,
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  systemPolicyIds: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    permissionType: "permission_type",
    scopeType: "scope_type",
    systemPolicyIds: "system_policy_ids",
  });
});

export function createRoleToJSON(createRole: CreateRole): string {
  return JSON.stringify(CreateRole$outboundSchema.parse(createRole));
}
