/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1cbbd32b037e
 */

export type CreateProductEnvironmentGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};
