/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 740309bed008
 */

export type CreateRoleGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};
