/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export type CreateUserGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

/**
 * The role to assign.
 */
export const CreateUserRole = {
  MasterAdmin: "master_admin",
  Admin: "admin",
  Billing: "billing",
  TechnicalAdmin: "technical_admin",
  Reports: "reports",
  MediaLibraryAdmin: "media_library_admin",
  MediaLibraryUser: "media_library_user",
} as const;
/**
 * The role to assign.
 */
export type CreateUserRole = ClosedEnum<typeof CreateUserRole>;

/**
 * User details.
 */
export type CreateUserRequestBody = {
  /**
   * The user's name.
   */
  name: string;
  /**
   * A unique email address, which serves as the login name and notification address.
   */
  email: string;
  /**
   * The role to assign.
   */
  role?: CreateUserRole | undefined;
  /**
   * A list of product environment IDs that this user can access. Ignored if the role is `master_admin`.
   *
   * @remarks
   * **Default**: all product environments.
   */
  subAccountIds?: Array<string> | undefined;
  /**
   * Whether the user is enabled. **Default**: true.
   *
   * @remarks
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const CreateUserRole$outboundSchema: z.ZodNativeEnum<
  typeof CreateUserRole
> = z.nativeEnum(CreateUserRole);

/** @internal */
export type CreateUserRequestBody$Outbound = {
  name: string;
  email: string;
  role?: string | undefined;
  sub_account_ids?: Array<string> | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const CreateUserRequestBody$outboundSchema: z.ZodType<
  CreateUserRequestBody$Outbound,
  z.ZodTypeDef,
  CreateUserRequestBody
> = z.object({
  name: z.string(),
  email: z.string(),
  role: CreateUserRole$outboundSchema.optional(),
  subAccountIds: z.array(z.string()).optional(),
  enabled: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    subAccountIds: "sub_account_ids",
  });
});

export function createUserRequestBodyToJSON(
  createUserRequestBody: CreateUserRequestBody,
): string {
  return JSON.stringify(
    CreateUserRequestBody$outboundSchema.parse(createUserRequestBody),
  );
}
