/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CustomPolicyResponseData,
  CustomPolicyResponseData$inboundSchema,
} from "./custompolicyresponsedata.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type CustomPolicyResponse = {
  data?: CustomPolicyResponseData | undefined;
};

/** @internal */
export const CustomPolicyResponse$inboundSchema: z.ZodType<
  CustomPolicyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: CustomPolicyResponseData$inboundSchema.optional(),
});

export function customPolicyResponseFromJSON(
  jsonString: string,
): SafeParseResult<CustomPolicyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomPolicyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomPolicyResponse' from JSON`,
  );
}
