/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$outboundSchema,
} from "./scopetypeenum.js";

export type CustomPolicy = {
  /**
   * A Cedar statement that permits or forbids a principal to perform an action on a resource. Refer to the [Permissions API guide](permissions_api_guide) for more information.
   */
  policyStatement: string;
  /**
   * A short description of the policy.
   */
  description?: string | null | undefined;
  /**
   * Specifies where the role/policy is applied, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  /**
   * The ID of a specific product environment, or "all" product environments, where the policy is applied. Required and only relevant if scope_type is "prodenv".
   *
   * @remarks
   * - <product_environment_id>
   * - all
   * *Note:* The "all" specification is relevant only when creating or updating a policy.
   */
  scopeId?: string | null | undefined;
  /**
   * The name assigned to the policy.
   */
  name: string;
  /**
   * Indicates whether the policy is currently active. Can be "true" (enabled) or "false" (disabled).
   */
  enabled?: boolean | null | undefined;
};

/** @internal */
export type CustomPolicy$Outbound = {
  policy_statement: string;
  description?: string | null | undefined;
  scope_type: string;
  scope_id?: string | null | undefined;
  name: string;
  enabled: boolean | null;
};

/** @internal */
export const CustomPolicy$outboundSchema: z.ZodType<
  CustomPolicy$Outbound,
  z.ZodTypeDef,
  CustomPolicy
> = z.object({
  policyStatement: z.string(),
  description: z.nullable(z.string()).optional(),
  scopeType: ScopeTypeEnum$outboundSchema,
  scopeId: z.nullable(z.string()).optional(),
  name: z.string(),
  enabled: z.nullable(z.boolean().default(true)),
}).transform((v) => {
  return remap$(v, {
    policyStatement: "policy_statement",
    scopeType: "scope_type",
    scopeId: "scope_id",
  });
});

export function customPolicyToJSON(customPolicy: CustomPolicy): string {
  return JSON.stringify(CustomPolicy$outboundSchema.parse(customPolicy));
}
