/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$inboundSchema,
} from "./scope-type-enum.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type CustomPolicyResponseData = {
  /**
   * The unique identifier of the policy.
   */
  id: string;
  /**
   * A Cedar policy that permits or forbids a certain action on a certain element to a principal (user, group, or API key).
   */
  policyStatement: string;
  /**
   * A short description of the policy.
   */
  description?: string | null | undefined;
  /**
   * Specifies where the role/policy is applied, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  /**
   * Returned only if the scope type is product environment. Can be "all" to represent all product environments or an ID of a specific product environment.
   */
  scopeId?: string | null | undefined;
  /**
   * The name of the policy
   */
  name: string;
  /**
   * Whether the policy is enabled or not
   */
  enabled: boolean;
  /**
   * Creation time of the policy in epoch time.
   */
  createdAt: number;
  /**
   * Last update time of the policy in epoch time.
   */
  updatedAt: number;
};

/** @internal */
export const CustomPolicyResponseData$inboundSchema: z.ZodMiniType<
  CustomPolicyResponseData,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    policy_statement: types.string(),
    description: z.optional(z.nullable(types.string())),
    scope_type: ScopeTypeEnum$inboundSchema,
    scope_id: z.optional(z.nullable(types.string())),
    name: types.string(),
    enabled: types.boolean(),
    created_at: types.number(),
    updated_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "policy_statement": "policyStatement",
      "scope_type": "scopeType",
      "scope_id": "scopeId",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function customPolicyResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<CustomPolicyResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomPolicyResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomPolicyResponseData' from JSON`,
  );
}
