/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CustomPolicyResponseData,
  CustomPolicyResponseData$inboundSchema,
} from "./custompolicyresponsedata.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type CustomPoliciesResponse = {
  /**
   * An array of custom policies.
   */
  data?: Array<CustomPolicyResponseData> | undefined;
  /**
   * When a request has more results to return, the next_cursor value is returned as part of the response. You can then specify this value as the cursor parameter of a following request.
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const CustomPoliciesResponse$inboundSchema: z.ZodType<
  CustomPoliciesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(CustomPolicyResponseData$inboundSchema).optional(),
  next_cursor: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "next_cursor": "nextCursor",
  });
});

export function customPoliciesResponseFromJSON(
  jsonString: string,
): SafeParseResult<CustomPoliciesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomPoliciesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomPoliciesResponse' from JSON`,
  );
}
