/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { ScopeTypeEnum, ScopeTypeEnum$inboundSchema } from "./scopetypeenum.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type CustomPolicyResponseData = {
  /**
   * The unique identifier of the policy.
   */
  id: string;
  /**
   * A Cedar policy that permits or forbids a certain action on a certain element to a principal (user, group, or API key).
   */
  policyStatement: string;
  /**
   * A short description of the policy.
   */
  description?: string | null | undefined;
  /**
   * Specifies where the role/policy is applied, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  /**
   * Returned only if the scope type is product environment. Can be "all" to represent all product environments or an ID of a specific product environment.
   */
  scopeId?: string | null | undefined;
  /**
   * The name of the policy
   */
  name: string;
  /**
   * Whether the policy is enabled or not
   */
  enabled: boolean;
  /**
   * Creation time of the policy in epoch time.
   */
  createdAt: number;
  /**
   * Last update time of the policy in epoch time.
   */
  updatedAt: number;
};

/** @internal */
export const CustomPolicyResponseData$inboundSchema: z.ZodType<
  CustomPolicyResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  policy_statement: z.string(),
  description: z.nullable(z.string()).optional(),
  scope_type: ScopeTypeEnum$inboundSchema,
  scope_id: z.nullable(z.string()).optional(),
  name: z.string(),
  enabled: z.boolean(),
  created_at: z.number().int(),
  updated_at: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "policy_statement": "policyStatement",
    "scope_type": "scopeType",
    "scope_id": "scopeId",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function customPolicyResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<CustomPolicyResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CustomPolicyResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CustomPolicyResponseData' from JSON`,
  );
}
