/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type DeleteUserGroupGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type DeleteUserGroupRequest = {
  /**
   * The ID of the user group.
   */
  groupId: string;
};

/** @internal */
export type DeleteUserGroupRequest$Outbound = {
  group_id: string;
};

/** @internal */
export const DeleteUserGroupRequest$outboundSchema: z.ZodMiniType<
  DeleteUserGroupRequest$Outbound,
  DeleteUserGroupRequest
> = z.pipe(
  z.object({
    groupId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      groupId: "group_id",
    });
  }),
);

export function deleteUserGroupRequestToJSON(
  deleteUserGroupRequest: DeleteUserGroupRequest,
): string {
  return JSON.stringify(
    DeleteUserGroupRequest$outboundSchema.parse(deleteUserGroupRequest),
  );
}
