/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type DeleteRoleGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type DeleteRoleRequest = {
  /**
   * A unique identifier for the role.
   */
  roleId: string;
  /**
   * Determines whether the role should be deleted when it has associated principals.
   *
   * @remarks
   * - `true`: Deletes the role even if it has associated principals.
   * - `false` (default): Prevents deletion if the role has associated principals. You must manually unassociate the principals before deleting the role.
   */
  force?: boolean | undefined;
};

/** @internal */
export type DeleteRoleRequest$Outbound = {
  role_id: string;
  force?: boolean | undefined;
};

/** @internal */
export const DeleteRoleRequest$outboundSchema: z.ZodType<
  DeleteRoleRequest$Outbound,
  z.ZodTypeDef,
  DeleteRoleRequest
> = z.object({
  roleId: z.string(),
  force: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    roleId: "role_id",
  });
});

export function deleteRoleRequestToJSON(
  deleteRoleRequest: DeleteRoleRequest,
): string {
  return JSON.stringify(
    DeleteRoleRequest$outboundSchema.parse(deleteRoleRequest),
  );
}
