/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5fa6b6802a0a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type DeleteRoleGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type DeleteRoleRequest = {
  /**
   * A unique identifier for the role.
   */
  roleId: string;
  /**
   * Determines whether the role should be deleted when it has associated principals.
   *
   * @remarks
   * - `true`: Deletes the role even if it has associated principals.
   * - `false` (default): Prevents deletion if the role has associated principals. You must manually unassociate the principals before deleting the role.
   */
  force?: boolean | undefined;
};

/** @internal */
export type DeleteRoleRequest$Outbound = {
  role_id: string;
  force?: boolean | undefined;
};

/** @internal */
export const DeleteRoleRequest$outboundSchema: z.ZodMiniType<
  DeleteRoleRequest$Outbound,
  DeleteRoleRequest
> = z.pipe(
  z.object({
    roleId: z.string(),
    force: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      roleId: "role_id",
    });
  }),
);

export function deleteRoleRequestToJSON(
  deleteRoleRequest: DeleteRoleRequest,
): string {
  return JSON.stringify(
    DeleteRoleRequest$outboundSchema.parse(deleteRoleRequest),
  );
}
