/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type DeleteAccessKeyGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type DeleteAccessKeyRequest = {
  /**
   * The ID of the product environment.
   */
  subAccountId: string;
  /**
   * The access key (api key).
   */
  key: string;
};

/** @internal */
export type DeleteAccessKeyRequest$Outbound = {
  sub_account_id: string;
  key: string;
};

/** @internal */
export const DeleteAccessKeyRequest$outboundSchema: z.ZodMiniType<
  DeleteAccessKeyRequest$Outbound,
  DeleteAccessKeyRequest
> = z.pipe(
  z.object({
    subAccountId: z.string(),
    key: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      subAccountId: "sub_account_id",
    });
  }),
);

export function deleteAccessKeyRequestToJSON(
  deleteAccessKeyRequest: DeleteAccessKeyRequest,
): string {
  return JSON.stringify(
    DeleteAccessKeyRequest$outboundSchema.parse(deleteAccessKeyRequest),
  );
}
