/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1f69dbd23f6a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type DeleteCustomPolicyGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type DeleteCustomPolicyRequest = {
  /**
   * A unique identifier for the custom permission policy.
   */
  policyId: string;
};

/** @internal */
export type DeleteCustomPolicyRequest$Outbound = {
  policy_id: string;
};

/** @internal */
export const DeleteCustomPolicyRequest$outboundSchema: z.ZodMiniType<
  DeleteCustomPolicyRequest$Outbound,
  DeleteCustomPolicyRequest
> = z.pipe(
  z.object({
    policyId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      policyId: "policy_id",
    });
  }),
);

export function deleteCustomPolicyRequestToJSON(
  deleteCustomPolicyRequest: DeleteCustomPolicyRequest,
): string {
  return JSON.stringify(
    DeleteCustomPolicyRequest$outboundSchema.parse(deleteCustomPolicyRequest),
  );
}
