/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 243d1cd63535
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type DeleteProductEnvironmentGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type DeleteProductEnvironmentRequest = {
  /**
   * The ID of the product environment.
   */
  subAccountId: string;
};

/** @internal */
export type DeleteProductEnvironmentRequest$Outbound = {
  sub_account_id: string;
};

/** @internal */
export const DeleteProductEnvironmentRequest$outboundSchema: z.ZodMiniType<
  DeleteProductEnvironmentRequest$Outbound,
  DeleteProductEnvironmentRequest
> = z.pipe(
  z.object({
    subAccountId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      subAccountId: "sub_account_id",
    });
  }),
);

export function deleteProductEnvironmentRequestToJSON(
  deleteProductEnvironmentRequest: DeleteProductEnvironmentRequest,
): string {
  return JSON.stringify(
    DeleteProductEnvironmentRequest$outboundSchema.parse(
      deleteProductEnvironmentRequest,
    ),
  );
}
