/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type DeleteProductEnvironmentGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type DeleteProductEnvironmentRequest = {
  /**
   * The ID of the product environment.
   */
  subAccountId: string;
};

/** @internal */
export type DeleteProductEnvironmentRequest$Outbound = {
  sub_account_id: string;
};

/** @internal */
export const DeleteProductEnvironmentRequest$outboundSchema: z.ZodType<
  DeleteProductEnvironmentRequest$Outbound,
  z.ZodTypeDef,
  DeleteProductEnvironmentRequest
> = z.object({
  subAccountId: z.string(),
}).transform((v) => {
  return remap$(v, {
    subAccountId: "sub_account_id",
  });
});

export function deleteProductEnvironmentRequestToJSON(
  deleteProductEnvironmentRequest: DeleteProductEnvironmentRequest,
): string {
  return JSON.stringify(
    DeleteProductEnvironmentRequest$outboundSchema.parse(
      deleteProductEnvironmentRequest,
    ),
  );
}
