/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type EffectivePolicy = {
  /**
   * The unique identifier of the permission policy.
   */
  id?: string | undefined;
  /**
   * A Cedar statement that permits or forbids a principal to perform an action on a resource. Refer to the [Permissions API guide](permissions_api_guide) for more information.
   */
  policyStatement?: string | undefined;
};

/** @internal */
export const EffectivePolicy$inboundSchema: z.ZodMiniType<
  EffectivePolicy,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    policy_statement: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "policy_statement": "policyStatement",
    });
  }),
);

export function effectivePolicyFromJSON(
  jsonString: string,
): SafeParseResult<EffectivePolicy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EffectivePolicy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EffectivePolicy' from JSON`,
  );
}
