/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  EffectivePolicy,
  EffectivePolicy$inboundSchema,
} from "./effectivepolicy.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type EffectiveRole = {
  /**
   * The unique identifier of the role.
   */
  id?: string | undefined;
  /**
   * A list of all the predefined permission policies that are associated with this role.
   */
  systemPolicies?: Array<EffectivePolicy> | undefined;
};

/** @internal */
export const EffectiveRole$inboundSchema: z.ZodType<
  EffectiveRole,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  system_policies: z.array(EffectivePolicy$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "system_policies": "systemPolicies",
  });
});

export function effectiveRoleFromJSON(
  jsonString: string,
): SafeParseResult<EffectiveRole, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EffectiveRole$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EffectiveRole' from JSON`,
  );
}
