/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  EffectivePolicy,
  EffectivePolicy$inboundSchema,
} from "./effectivepolicy.js";
import { PrincipalRole, PrincipalRole$inboundSchema } from "./principalrole.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type Data = {
  principals?: Array<PrincipalRole> | undefined;
  customPolicies?: Array<EffectivePolicy> | undefined;
};

export type EffectivePoliciesResponse = {
  data?: Data | undefined;
};

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    principals: z.array(PrincipalRole$inboundSchema).optional(),
    custom_policies: z.array(EffectivePolicy$inboundSchema).optional(),
  }).transform((v) => {
    return remap$(v, {
      "custom_policies": "customPolicies",
    });
  });

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const EffectivePoliciesResponse$inboundSchema: z.ZodType<
  EffectivePoliciesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => Data$inboundSchema).optional(),
});

export function effectivePoliciesResponseFromJSON(
  jsonString: string,
): SafeParseResult<EffectivePoliciesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EffectivePoliciesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EffectivePoliciesResponse' from JSON`,
  );
}
