/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  EffectivePolicy,
  EffectivePolicy$inboundSchema,
} from "./effective-policy.js";
import {
  PrincipalRole,
  PrincipalRole$inboundSchema,
} from "./principal-role.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type Data = {
  principals?: Array<PrincipalRole> | undefined;
  customPolicies?: Array<EffectivePolicy> | undefined;
};

export type EffectivePoliciesResponse = {
  data?: Data | undefined;
};

/** @internal */
export const Data$inboundSchema: z.ZodMiniType<Data, unknown> = z.pipe(
  z.object({
    principals: types.optional(z.array(PrincipalRole$inboundSchema)),
    custom_policies: types.optional(z.array(EffectivePolicy$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "custom_policies": "customPolicies",
    });
  }),
);

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const EffectivePoliciesResponse$inboundSchema: z.ZodMiniType<
  EffectivePoliciesResponse,
  unknown
> = z.object({
  data: types.optional(z.lazy(() => Data$inboundSchema)),
});

export function effectivePoliciesResponseFromJSON(
  jsonString: string,
): SafeParseResult<EffectivePoliciesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EffectivePoliciesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EffectivePoliciesResponse' from JSON`,
  );
}
