/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { CldProvisioningError } from "./cld-provisioning-error.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ErrorT = {
  message?: string | undefined;
};

/**
 * Bad request.
 */
export type ErrorResponseData = {
  error?: ErrorT | undefined;
};

/**
 * Bad request.
 */
export class ErrorResponse extends CldProvisioningError {
  error?: ErrorT | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorResponseData;

  constructor(
    err: ErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "ErrorResponse";
  }
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodMiniType<ErrorT, unknown> = z.object({
  message: types.optional(types.string()),
});

export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const ErrorResponse$inboundSchema: z.ZodMiniType<
  ErrorResponse,
  unknown
> = z.pipe(
  z.object({
    error: types.optional(z.lazy(() => ErrorT$inboundSchema)),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new ErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
