/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  AccessKeyRequest,
  AccessKeyRequest$Outbound,
  AccessKeyRequest$outboundSchema,
} from "./access-key-request.js";

export type GenerateAccessKeyGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GenerateAccessKeyRequest = {
  /**
   * The ID of the product environment.
   */
  subAccountId: string;
  /**
   * Access key details.
   */
  accessKeyRequest: AccessKeyRequest;
};

/** @internal */
export type GenerateAccessKeyRequest$Outbound = {
  sub_account_id: string;
  AccessKeyRequest: AccessKeyRequest$Outbound;
};

/** @internal */
export const GenerateAccessKeyRequest$outboundSchema: z.ZodMiniType<
  GenerateAccessKeyRequest$Outbound,
  GenerateAccessKeyRequest
> = z.pipe(
  z.object({
    subAccountId: z.string(),
    accessKeyRequest: AccessKeyRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      subAccountId: "sub_account_id",
      accessKeyRequest: "AccessKeyRequest",
    });
  }),
);

export function generateAccessKeyRequestToJSON(
  generateAccessKeyRequest: GenerateAccessKeyRequest,
): string {
  return JSON.stringify(
    GenerateAccessKeyRequest$outboundSchema.parse(generateAccessKeyRequest),
  );
}
