/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type GetUserGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetUserRequest = {
  /**
   * The ID of the user.
   */
  userId: string;
};

/** @internal */
export type GetUserRequest$Outbound = {
  user_id: string;
};

/** @internal */
export const GetUserRequest$outboundSchema: z.ZodMiniType<
  GetUserRequest$Outbound,
  GetUserRequest
> = z.pipe(
  z.object({
    userId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      userId: "user_id",
    });
  }),
);

export function getUserRequestToJSON(getUserRequest: GetUserRequest): string {
  return JSON.stringify(GetUserRequest$outboundSchema.parse(getUserRequest));
}
