/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type GetSubAccountsForUserGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetSubAccountsForUserRequest = {
  /**
   * The ID of the user.
   */
  userId: string;
};

/** @internal */
export type GetSubAccountsForUserRequest$Outbound = {
  user_id: string;
};

/** @internal */
export const GetSubAccountsForUserRequest$outboundSchema: z.ZodMiniType<
  GetSubAccountsForUserRequest$Outbound,
  GetSubAccountsForUserRequest
> = z.pipe(
  z.object({
    userId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      userId: "user_id",
    });
  }),
);

export function getSubAccountsForUserRequestToJSON(
  getSubAccountsForUserRequest: GetSubAccountsForUserRequest,
): string {
  return JSON.stringify(
    GetSubAccountsForUserRequest$outboundSchema.parse(
      getSubAccountsForUserRequest,
    ),
  );
}
