/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type GetCustomPolicyGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetCustomPolicyRequest = {
  /**
   * A unique identifier for the custom permission policy.
   */
  policyId: string;
};

/** @internal */
export type GetCustomPolicyRequest$Outbound = {
  policy_id: string;
};

/** @internal */
export const GetCustomPolicyRequest$outboundSchema: z.ZodMiniType<
  GetCustomPolicyRequest$Outbound,
  GetCustomPolicyRequest
> = z.pipe(
  z.object({
    policyId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      policyId: "policy_id",
    });
  }),
);

export function getCustomPolicyRequestToJSON(
  getCustomPolicyRequest: GetCustomPolicyRequest,
): string {
  return JSON.stringify(
    GetCustomPolicyRequest$outboundSchema.parse(getCustomPolicyRequest),
  );
}
