/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ManagementTypeEnum,
  ManagementTypeEnum$outboundSchema,
} from "./management-type-enum.js";
import {
  PermissionTypeEnum,
  PermissionTypeEnum$outboundSchema,
} from "./permission-type-enum.js";
import {
  PrincipalTypeEnum,
  PrincipalTypeEnum$outboundSchema,
} from "./principal-type-enum.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$outboundSchema,
} from "./scope-type-enum.js";

export type GetPrincipalRolesGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetPrincipalRolesRequest = {
  /**
   * The type of principal you want to retrieve roles or permission policies for.
   */
  principalType: PrincipalTypeEnum;
  /**
   * The unique identifier of the principal you want to retrieve roles or permission policies for.
   *
   * @remarks
   *
   * **Notes:**
   *
   * * This parameter is mandatory if `principal_type` is provided.
   * * Ensure the specified ID belongs to a principle of the specified type.
   */
  principalId: string;
  /**
   * Specifies whether to retrieve roles whose permissions apply globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
   */
  permissionType: PermissionTypeEnum;
  /**
   * Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
   */
  managementType?: ManagementTypeEnum | undefined;
  /**
   * Specifies the level for retrieving policies or roles, either at the account level or within product environments.
   */
  scopeType?: ScopeTypeEnum | undefined;
  /**
   * The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is "prodenv".
   *
   * @remarks
   * - <product_environment_id>
   */
  scopeId?: string | undefined;
  /**
   * * In the **Get role** endpoint, the specified `folder_id` is included in the `policy_statement` parameter of the response. If no `folder_id` is specified, the `policy_statement` shows a placeholder for the `folder_id` where relevant.
   *
   * @remarks
   * * In the **Get a principal's roles**, **Get a role's principals**, and **Inspect** endpoints, the results are filtered by the specified `folder_id`. Only roles or principals with `policy_statement` parameters associated with that `folder_id` are returned.
   */
  folderId?: string | undefined;
  /**
   * Not currently supported.
   */
  assetId?: string | undefined;
  /**
   * * In the **Get role** endpoint, the specified `collection_id` is included in the `policy_statement` parameter of the response. If no `collection_id` is specified, the `policy_statement` shows a placeholder for the `collection_id` where relevant.
   *
   * @remarks
   * * In the **Get a principal's roles** and **Get a role's principals** endpoints, the results are filtered by the specified `collection_id`. Only roles or principals with `policy_statement` parameters associated with that `collection_id` are returned.
   */
  collectionId?: string | undefined;
  /**
   * The type of content instance the role applies to, either `folder_id` or `collection_id`. Use together with `param_value` to retrieve role assignments as they apply to a specific instance.
   */
  paramKey?: Array<string> | undefined;
  /**
   * The ID of the content instance (for example, a specific folder or collection). Use together with param_key to retrieve roles as they apply to a specific instance.
   */
  paramValue?: Array<string> | undefined;
};

/** @internal */
export type GetPrincipalRolesRequest$Outbound = {
  principal_type: string;
  principal_id: string;
  permission_type: string;
  management_type?: string | undefined;
  scope_type?: string | undefined;
  scope_id?: string | undefined;
  folder_id?: string | undefined;
  asset_id?: string | undefined;
  collection_id?: string | undefined;
  param_key?: Array<string> | undefined;
  param_value?: Array<string> | undefined;
};

/** @internal */
export const GetPrincipalRolesRequest$outboundSchema: z.ZodMiniType<
  GetPrincipalRolesRequest$Outbound,
  GetPrincipalRolesRequest
> = z.pipe(
  z.object({
    principalType: PrincipalTypeEnum$outboundSchema,
    principalId: z.string(),
    permissionType: PermissionTypeEnum$outboundSchema,
    managementType: z.optional(ManagementTypeEnum$outboundSchema),
    scopeType: z.optional(ScopeTypeEnum$outboundSchema),
    scopeId: z.optional(z.string()),
    folderId: z.optional(z.string()),
    assetId: z.optional(z.string()),
    collectionId: z.optional(z.string()),
    paramKey: z.optional(z.array(z.string())),
    paramValue: z.optional(z.array(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      principalType: "principal_type",
      principalId: "principal_id",
      permissionType: "permission_type",
      managementType: "management_type",
      scopeType: "scope_type",
      scopeId: "scope_id",
      folderId: "folder_id",
      assetId: "asset_id",
      collectionId: "collection_id",
      paramKey: "param_key",
      paramValue: "param_value",
    });
  }),
);

export function getPrincipalRolesRequestToJSON(
  getPrincipalRolesRequest: GetPrincipalRolesRequest,
): string {
  return JSON.stringify(
    GetPrincipalRolesRequest$outboundSchema.parse(getPrincipalRolesRequest),
  );
}
