/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4396d28d4d05
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type GetProductEnvironmentsGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetProductEnvironmentsRequest = {
  /**
   * Whether to only return enabled product environments (true) or disabled product environments (false).
   *
   * @remarks
   * **Default**: all product environments are returned (both enabled and disabled).
   */
  enabled?: boolean | undefined;
  /**
   * A list of up to 100 product environment IDs. When provided, other parameters are ignored.
   */
  ids?: Array<string> | undefined;
  /**
   * A list of up to 100 product environment cloud names.
   */
  cloudNames?: Array<string> | undefined;
  /**
   * Returns product environments where the name begins with the specified case-insensitive string.
   */
  prefix?: string | undefined;
};

/** @internal */
export type GetProductEnvironmentsRequest$Outbound = {
  enabled?: boolean | undefined;
  ids?: Array<string> | undefined;
  cloud_names?: Array<string> | undefined;
  prefix?: string | undefined;
};

/** @internal */
export const GetProductEnvironmentsRequest$outboundSchema: z.ZodMiniType<
  GetProductEnvironmentsRequest$Outbound,
  GetProductEnvironmentsRequest
> = z.pipe(
  z.object({
    enabled: z.optional(z.boolean()),
    ids: z.optional(z.array(z.string())),
    cloudNames: z.optional(z.array(z.string())),
    prefix: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cloudNames: "cloud_names",
    });
  }),
);

export function getProductEnvironmentsRequestToJSON(
  getProductEnvironmentsRequest: GetProductEnvironmentsRequest,
): string {
  return JSON.stringify(
    GetProductEnvironmentsRequest$outboundSchema.parse(
      getProductEnvironmentsRequest,
    ),
  );
}
