/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  PrincipalTypeEnum,
  PrincipalTypeEnum$outboundSchema,
} from "./principal-type-enum.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$outboundSchema,
} from "./scope-type-enum.js";

export type GetEffectivePoliciesGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetEffectivePoliciesRequest = {
  /**
   * Specifies the level for retrieving policies or roles, either at the account level or within product environments.
   */
  scopeType?: ScopeTypeEnum | undefined;
  /**
   * The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is "prodenv".
   *
   * @remarks
   * - <product_environment_id>
   */
  scopeId?: string | undefined;
  /**
   * The type of principal you want to retrieve roles or permission policies for.
   */
  principalType?: PrincipalTypeEnum | undefined;
  /**
   * The unique identifier of the principal you want to retrieve roles or permission policies for.
   *
   * @remarks
   *
   * **Notes:**
   *
   * * This parameter is mandatory if `principal_type` is provided.
   * * Ensure the specified ID belongs to a principle of the specified type.
   */
  principalId?: string | undefined;
};

/** @internal */
export type GetEffectivePoliciesRequest$Outbound = {
  scope_type?: string | undefined;
  scope_id?: string | undefined;
  principal_type?: string | undefined;
  principal_id?: string | undefined;
};

/** @internal */
export const GetEffectivePoliciesRequest$outboundSchema: z.ZodMiniType<
  GetEffectivePoliciesRequest$Outbound,
  GetEffectivePoliciesRequest
> = z.pipe(
  z.object({
    scopeType: z.optional(ScopeTypeEnum$outboundSchema),
    scopeId: z.optional(z.string()),
    principalType: z.optional(PrincipalTypeEnum$outboundSchema),
    principalId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      scopeType: "scope_type",
      scopeId: "scope_id",
      principalType: "principal_type",
      principalId: "principal_id",
    });
  }),
);

export function getEffectivePoliciesRequestToJSON(
  getEffectivePoliciesRequest: GetEffectivePoliciesRequest,
): string {
  return JSON.stringify(
    GetEffectivePoliciesRequest$outboundSchema.parse(
      getEffectivePoliciesRequest,
    ),
  );
}
