/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$outboundSchema,
} from "./scope-type-enum.js";

export type GetCustomPoliciesGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetCustomPoliciesRequest = {
  /**
   * Specifies the level for retrieving policies or roles, either at the account level or within product environments.
   */
  scopeType?: ScopeTypeEnum | undefined;
  /**
   * The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is "prodenv".
   *
   * @remarks
   * - <product_environment_id>
   */
  scopeId?: string | undefined;
  /**
   * Filter policies by enabled status (true/false).
   */
  enabled?: boolean | null | undefined;
  /**
   * A pagination cursor for fetching subsequent results.
   */
  cursor?: string | undefined;
};

/** @internal */
export type GetCustomPoliciesRequest$Outbound = {
  scope_type?: string | undefined;
  scope_id?: string | undefined;
  enabled?: boolean | null | undefined;
  cursor?: string | undefined;
};

/** @internal */
export const GetCustomPoliciesRequest$outboundSchema: z.ZodMiniType<
  GetCustomPoliciesRequest$Outbound,
  GetCustomPoliciesRequest
> = z.pipe(
  z.object({
    scopeType: z.optional(ScopeTypeEnum$outboundSchema),
    scopeId: z.optional(z.string()),
    enabled: z.optional(z.nullable(z.boolean())),
    cursor: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      scopeType: "scope_type",
      scopeId: "scope_id",
    });
  }),
);

export function getCustomPoliciesRequestToJSON(
  getCustomPoliciesRequest: GetCustomPoliciesRequest,
): string {
  return JSON.stringify(
    GetCustomPoliciesRequest$outboundSchema.parse(getCustomPoliciesRequest),
  );
}
