/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 76c8ed3ec1c5
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type GetGroupsForUserGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetGroupsForUserRequest = {
  /**
   * The ID of the user.
   */
  userId: string;
};

/** @internal */
export type GetGroupsForUserRequest$Outbound = {
  user_id: string;
};

/** @internal */
export const GetGroupsForUserRequest$outboundSchema: z.ZodMiniType<
  GetGroupsForUserRequest$Outbound,
  GetGroupsForUserRequest
> = z.pipe(
  z.object({
    userId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      userId: "user_id",
    });
  }),
);

export function getGroupsForUserRequestToJSON(
  getGroupsForUserRequest: GetGroupsForUserRequest,
): string {
  return JSON.stringify(
    GetGroupsForUserRequest$outboundSchema.parse(getGroupsForUserRequest),
  );
}
