/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  PermissionTypeEnum,
  PermissionTypeEnum$outboundSchema,
} from "./permission-type-enum.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$outboundSchema,
} from "./scope-type-enum.js";

export type GetSystemPoliciesGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetSystemPoliciesRequest = {
  /**
   * Specifies whether to retrieve roles whose permissions apply globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
   */
  permissionType?: PermissionTypeEnum | undefined;
  /**
   * Specifies the level for retrieving policies or roles, either at the account level or within product environments.
   */
  scopeType?: ScopeTypeEnum | undefined;
};

/** @internal */
export type GetSystemPoliciesRequest$Outbound = {
  permission_type?: string | undefined;
  scope_type?: string | undefined;
};

/** @internal */
export const GetSystemPoliciesRequest$outboundSchema: z.ZodMiniType<
  GetSystemPoliciesRequest$Outbound,
  GetSystemPoliciesRequest
> = z.pipe(
  z.object({
    permissionType: z.optional(PermissionTypeEnum$outboundSchema),
    scopeType: z.optional(ScopeTypeEnum$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      permissionType: "permission_type",
      scopeType: "scope_type",
    });
  }),
);

export function getSystemPoliciesRequestToJSON(
  getSystemPoliciesRequest: GetSystemPoliciesRequest,
): string {
  return JSON.stringify(
    GetSystemPoliciesRequest$outboundSchema.parse(getSystemPoliciesRequest),
  );
}
