/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type GetUsersInUserGroupGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetUsersInUserGroupRequest = {
  /**
   * The ID of the user group.
   */
  groupId: string;
};

/** @internal */
export type GetUsersInUserGroupRequest$Outbound = {
  group_id: string;
};

/** @internal */
export const GetUsersInUserGroupRequest$outboundSchema: z.ZodMiniType<
  GetUsersInUserGroupRequest$Outbound,
  GetUsersInUserGroupRequest
> = z.pipe(
  z.object({
    groupId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      groupId: "group_id",
    });
  }),
);

export function getUsersInUserGroupRequestToJSON(
  getUsersInUserGroupRequest: GetUsersInUserGroupRequest,
): string {
  return JSON.stringify(
    GetUsersInUserGroupRequest$outboundSchema.parse(getUsersInUserGroupRequest),
  );
}
