/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

export type GetUsersGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

/**
 * Whether to return users who last logged in within the specified date range (include) or those who didn't
 *
 * @remarks
 * last log in within the range (exclude). **Possible values**: `include`, `exclude`. **Default**: `include`.
 */
export const UnionType = {
  Include: "include",
  Exclude: "exclude",
} as const;
/**
 * Whether to return users who last logged in within the specified date range (include) or those who didn't
 *
 * @remarks
 * last log in within the range (exclude). **Possible values**: `include`, `exclude`. **Default**: `include`.
 */
export type UnionType = ClosedEnum<typeof UnionType>;

/**
 * Control the order of returned users. **Possible values**: `desc` (default), `asc`.
 *
 * @remarks
 */
export const QueryParamSortOrder = {
  Desc: "desc",
  Asc: "asc",
} as const;
/**
 * Control the order of returned users. **Possible values**: `desc` (default), `asc`.
 *
 * @remarks
 */
export type QueryParamSortOrder = ClosedEnum<typeof QueryParamSortOrder>;

export const QueryParamSortBy = {
  Name: "name",
  Role: "role",
  Status: "status",
  Activity: "activity",
  CreatedAt: "created_at",
} as const;
export type QueryParamSortBy = ClosedEnum<typeof QueryParamSortBy>;

export type GetUsersRequest = {
  /**
   * Whether to return pending users. **Default**: `false` (all users)
   *
   * @remarks
   */
  pending?: boolean | undefined;
  /**
   * A list of up to 100 user IDs.  When provided, other parameters are ignored.
   */
  ids?: Array<string> | undefined;
  /**
   * A list of up to 100 user Emails.  When provided, other parameters are ignored.
   */
  emails?: Array<string> | undefined;
  /**
   * Returns users where the name begins with the specified case-insensitive string.
   */
  prefix?: string | undefined;
  /**
   * Only returns users who have access to the specified account.
   */
  subAccountId?: string | undefined;
  /**
   * Specifies a date range for last login.
   */
  lastLogin?: boolean | undefined;
  /**
   * All last logins after this date, given in the format: yyyy-mm-dd.
   *
   * @remarks
   */
  from?: Date | undefined;
  /**
   * All last logins before this date, given in the format: yyyy-mm-dd.
   *
   * @remarks
   */
  to?: Date | undefined;
  /**
   * Whether to return users who last logged in within the specified date range (include) or those who didn't
   *
   * @remarks
   * last log in within the range (exclude). **Possible values**: `include`, `exclude`. **Default**: `include`.
   */
  unionType?: UnionType | undefined;
  /**
   * Control the order of returned users. **Possible values**: `desc` (default), `asc`.
   *
   * @remarks
   */
  sortOrder?: QueryParamSortOrder | undefined;
  sortBy?: QueryParamSortBy | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
};

/** @internal */
export const UnionType$outboundSchema: z.ZodMiniEnum<typeof UnionType> = z.enum(
  UnionType,
);

/** @internal */
export const QueryParamSortOrder$outboundSchema: z.ZodMiniEnum<
  typeof QueryParamSortOrder
> = z.enum(QueryParamSortOrder);

/** @internal */
export const QueryParamSortBy$outboundSchema: z.ZodMiniEnum<
  typeof QueryParamSortBy
> = z.enum(QueryParamSortBy);

/** @internal */
export type GetUsersRequest$Outbound = {
  pending?: boolean | undefined;
  ids?: Array<string> | undefined;
  emails?: Array<string> | undefined;
  prefix?: string | undefined;
  sub_account_id?: string | undefined;
  last_login?: boolean | undefined;
  from?: string | undefined;
  to?: string | undefined;
  union_type?: string | undefined;
  sort_order?: string | undefined;
  sort_by?: string | undefined;
  page?: number | undefined;
  page_size?: number | undefined;
};

/** @internal */
export const GetUsersRequest$outboundSchema: z.ZodMiniType<
  GetUsersRequest$Outbound,
  GetUsersRequest
> = z.pipe(
  z.object({
    pending: z.optional(z.boolean()),
    ids: z.optional(z.array(z.string())),
    emails: z.optional(z.array(z.string())),
    prefix: z.optional(z.string()),
    subAccountId: z.optional(z.string()),
    lastLogin: z.optional(z.boolean()),
    from: z.optional(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
    to: z.optional(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
    unionType: z.optional(UnionType$outboundSchema),
    sortOrder: z.optional(QueryParamSortOrder$outboundSchema),
    sortBy: z.optional(QueryParamSortBy$outboundSchema),
    page: z.optional(z.int()),
    pageSize: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      subAccountId: "sub_account_id",
      lastLogin: "last_login",
      unionType: "union_type",
      sortOrder: "sort_order",
      sortBy: "sort_by",
      pageSize: "page_size",
    });
  }),
);

export function getUsersRequestToJSON(
  getUsersRequest: GetUsersRequest,
): string {
  return JSON.stringify(GetUsersRequest$outboundSchema.parse(getUsersRequest));
}
