/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type GetBillingUsageGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetBillingUsageRequest = {
  /**
   * The year to retrieve billing usage for. Behavior depends on subscription type (see above).
   */
  year?: number | undefined;
  /**
   * Whether to include usage details by product environment. **Default**: false.
   *
   * @remarks
   */
  includeProdenvBreakdown?: boolean | undefined;
};

/** @internal */
export type GetBillingUsageRequest$Outbound = {
  year?: number | undefined;
  include_prodenv_breakdown?: boolean | undefined;
};

/** @internal */
export const GetBillingUsageRequest$outboundSchema: z.ZodType<
  GetBillingUsageRequest$Outbound,
  z.ZodTypeDef,
  GetBillingUsageRequest
> = z.object({
  year: z.number().int().optional(),
  includeProdenvBreakdown: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    includeProdenvBreakdown: "include_prodenv_breakdown",
  });
});

export function getBillingUsageRequestToJSON(
  getBillingUsageRequest: GetBillingUsageRequest,
): string {
  return JSON.stringify(
    GetBillingUsageRequest$outboundSchema.parse(getBillingUsageRequest),
  );
}
