/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type GetProductEnvironmentGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetProductEnvironmentRequest = {
  /**
   * The ID of the product environment.
   */
  subAccountId: string;
};

/** @internal */
export type GetProductEnvironmentRequest$Outbound = {
  sub_account_id: string;
};

/** @internal */
export const GetProductEnvironmentRequest$outboundSchema: z.ZodType<
  GetProductEnvironmentRequest$Outbound,
  z.ZodTypeDef,
  GetProductEnvironmentRequest
> = z.object({
  subAccountId: z.string(),
}).transform((v) => {
  return remap$(v, {
    subAccountId: "sub_account_id",
  });
});

export function getProductEnvironmentRequestToJSON(
  getProductEnvironmentRequest: GetProductEnvironmentRequest,
): string {
  return JSON.stringify(
    GetProductEnvironmentRequest$outboundSchema.parse(
      getProductEnvironmentRequest,
    ),
  );
}
