/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ManagementTypeEnum,
  ManagementTypeEnum$outboundSchema,
} from "./managementtypeenum.js";
import {
  PermissionTypeEnum,
  PermissionTypeEnum$outboundSchema,
} from "./permissiontypeenum.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$outboundSchema,
} from "./scopetypeenum.js";

export type GetRolesGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetRolesRequest = {
  /**
   * Specifies the level for retrieving policies or roles, either at the account level or within product environments.
   */
  scopeType?: ScopeTypeEnum | undefined;
  /**
   * Specifies whether to retrieve roles whose permissions apply globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
   */
  permissionType: PermissionTypeEnum;
  /**
   * Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
   */
  managementType?: ManagementTypeEnum | undefined;
  /**
   * For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
   *
   * @remarks
   * - The content type can be: `folder_id` or `collection_id`.
   * - When assigning the role, provide the instance, e.g. `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
   */
  policyParameters?: Array<string> | undefined;
};

/** @internal */
export type GetRolesRequest$Outbound = {
  scope_type?: string | undefined;
  permission_type: string;
  management_type?: string | undefined;
  policy_parameters?: Array<string> | undefined;
};

/** @internal */
export const GetRolesRequest$outboundSchema: z.ZodType<
  GetRolesRequest$Outbound,
  z.ZodTypeDef,
  GetRolesRequest
> = z.object({
  scopeType: ScopeTypeEnum$outboundSchema.optional(),
  permissionType: PermissionTypeEnum$outboundSchema,
  managementType: ManagementTypeEnum$outboundSchema.optional(),
  policyParameters: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    scopeType: "scope_type",
    permissionType: "permission_type",
    managementType: "management_type",
    policyParameters: "policy_parameters",
  });
});

export function getRolesRequestToJSON(
  getRolesRequest: GetRolesRequest,
): string {
  return JSON.stringify(GetRolesRequest$outboundSchema.parse(getRolesRequest));
}
