/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type GetUsersInUserGroupGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type GetUsersInUserGroupRequest = {
  /**
   * The ID of the user group.
   */
  groupId: string;
};

/** @internal */
export type GetUsersInUserGroupRequest$Outbound = {
  group_id: string;
};

/** @internal */
export const GetUsersInUserGroupRequest$outboundSchema: z.ZodType<
  GetUsersInUserGroupRequest$Outbound,
  z.ZodTypeDef,
  GetUsersInUserGroupRequest
> = z.object({
  groupId: z.string(),
}).transform((v) => {
  return remap$(v, {
    groupId: "group_id",
  });
});

export function getUsersInUserGroupRequestToJSON(
  getUsersInUserGroupRequest: GetUsersInUserGroupRequest,
): string {
  return JSON.stringify(
    GetUsersInUserGroupRequest$outboundSchema.parse(getUsersInUserGroupRequest),
  );
}
