/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 96bba1a2365a
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  Principal,
  Principal$Outbound,
  Principal$outboundSchema,
} from "./principal.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$outboundSchema,
} from "./scope-type-enum.js";

export type InspectRequestPolicyParameters = {};

export type InspectRequest = {
  /**
   * Specifies where the role/policy is applied, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  scopeId?: string | undefined;
  principals: Array<Principal>;
  policyParameters?: InspectRequestPolicyParameters | undefined;
  cursor?: string | undefined;
};

/** @internal */
export type InspectRequestPolicyParameters$Outbound = {};

/** @internal */
export const InspectRequestPolicyParameters$outboundSchema: z.ZodMiniType<
  InspectRequestPolicyParameters$Outbound,
  InspectRequestPolicyParameters
> = z.object({});

export function inspectRequestPolicyParametersToJSON(
  inspectRequestPolicyParameters: InspectRequestPolicyParameters,
): string {
  return JSON.stringify(
    InspectRequestPolicyParameters$outboundSchema.parse(
      inspectRequestPolicyParameters,
    ),
  );
}

/** @internal */
export type InspectRequest$Outbound = {
  scope_type: string;
  scope_id?: string | undefined;
  principals: Array<Principal$Outbound>;
  policy_parameters?: InspectRequestPolicyParameters$Outbound | undefined;
  cursor?: string | undefined;
};

/** @internal */
export const InspectRequest$outboundSchema: z.ZodMiniType<
  InspectRequest$Outbound,
  InspectRequest
> = z.pipe(
  z.object({
    scopeType: ScopeTypeEnum$outboundSchema,
    scopeId: z.optional(z.string()),
    principals: z.array(Principal$outboundSchema),
    policyParameters: z.optional(
      z.lazy(() => InspectRequestPolicyParameters$outboundSchema),
    ),
    cursor: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      scopeType: "scope_type",
      scopeId: "scope_id",
      policyParameters: "policy_parameters",
    });
  }),
);

export function inspectRequestToJSON(inspectRequest: InspectRequest): string {
  return JSON.stringify(InspectRequest$outboundSchema.parse(inspectRequest));
}
