/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6dac4394d64c
 */

export type InspectMultipleGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};
