/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3e76b4c5e231
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  PrincipalTypeEnum,
  PrincipalTypeEnum$outboundSchema,
} from "./principal-type-enum.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$outboundSchema,
} from "./scope-type-enum.js";

export type InspectGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type InspectRequest1 = {
  /**
   * Specifies the level for retrieving policies or roles, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  /**
   * The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is "prodenv".
   *
   * @remarks
   * - <product_environment_id>
   */
  scopeId?: string | undefined;
  /**
   * The type of principal you want to retrieve roles or permission policies for.
   */
  principalType?: PrincipalTypeEnum | undefined;
  /**
   * The unique identifier of the principal you want to retrieve roles or permission policies for.
   *
   * @remarks
   *
   * **Notes:**
   *
   * * This parameter is mandatory if `principal_type` is provided.
   * * Ensure the specified ID belongs to a principle of the specified type.
   */
  principalId?: string | undefined;
  /**
   * * In the **Get role** endpoint, the specified `folder_id` is included in the `policy_statement` parameter of the response. If no `folder_id` is specified, the `policy_statement` shows a placeholder for the `folder_id` where relevant.
   *
   * @remarks
   * * In the **Get a principal's roles**, **Get a role's principals**, and **Inspect** endpoints, the results are filtered by the specified `folder_id`. Only roles or principals with `policy_statement` parameters associated with that `folder_id` are returned.
   */
  folderId?: string | undefined;
  /**
   * Not currently supported.
   */
  assetId?: string | undefined;
  /**
   * * In the **Get role** endpoint, the specified `collection_id` is included in the `policy_statement` parameter of the response. If no `collection_id` is specified, the `policy_statement` shows a placeholder for the `collection_id` where relevant.
   *
   * @remarks
   * * In the **Get a principal's roles** and **Get a role's principals** endpoints, the results are filtered by the specified `collection_id`. Only roles or principals with `policy_statement` parameters associated with that `collection_id` are returned.
   */
  collectionId?: string | undefined;
  /**
   * The type of content instance the role applies to, either `folder_id` or `collection_id`. Use together with `param_value` to retrieve role assignments as they apply to a specific instance.
   */
  paramKey?: Array<string> | undefined;
  /**
   * The ID of the content instance (for example, a specific folder or collection). Use together with param_key to retrieve roles as they apply to a specific instance.
   */
  paramValue?: Array<string> | undefined;
  /**
   * A pagination cursor for fetching subsequent results.
   */
  cursor?: string | undefined;
};

/** @internal */
export type InspectRequest1$Outbound = {
  scope_type: string;
  scope_id?: string | undefined;
  principal_type?: string | undefined;
  principal_id?: string | undefined;
  folder_id?: string | undefined;
  asset_id?: string | undefined;
  collection_id?: string | undefined;
  param_key?: Array<string> | undefined;
  param_value?: Array<string> | undefined;
  cursor?: string | undefined;
};

/** @internal */
export const InspectRequest1$outboundSchema: z.ZodMiniType<
  InspectRequest1$Outbound,
  InspectRequest1
> = z.pipe(
  z.object({
    scopeType: ScopeTypeEnum$outboundSchema,
    scopeId: z.optional(z.string()),
    principalType: z.optional(PrincipalTypeEnum$outboundSchema),
    principalId: z.optional(z.string()),
    folderId: z.optional(z.string()),
    assetId: z.optional(z.string()),
    collectionId: z.optional(z.string()),
    paramKey: z.optional(z.array(z.string())),
    paramValue: z.optional(z.array(z.string())),
    cursor: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      scopeType: "scope_type",
      scopeId: "scope_id",
      principalType: "principal_type",
      principalId: "principal_id",
      folderId: "folder_id",
      assetId: "asset_id",
      collectionId: "collection_id",
      paramKey: "param_key",
      paramValue: "param_value",
    });
  }),
);

export function inspectRequest1ToJSON(
  inspectRequest1: InspectRequest1,
): string {
  return JSON.stringify(InspectRequest1$outboundSchema.parse(inspectRequest1));
}
