/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 29b2fde1a658
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
 */
export const ManagementTypeEnum = {
  System: "system",
  Custom: "custom",
} as const;
/**
 * Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
 */
export type ManagementTypeEnum = OpenEnum<typeof ManagementTypeEnum>;

/** @internal */
export const ManagementTypeEnum$inboundSchema: z.ZodMiniType<
  ManagementTypeEnum,
  unknown
> = openEnums.inboundSchema(ManagementTypeEnum);
/** @internal */
export const ManagementTypeEnum$outboundSchema: z.ZodMiniType<
  string,
  ManagementTypeEnum
> = openEnums.outboundSchema(ManagementTypeEnum);
