/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 7db1dca4974b
 */

import * as z from "zod/v4-mini";
import * as types from "../types/primitives.js";
import { CldProvisioningError } from "./cld-provisioning-error.js";
import {
  PermissionsError,
  PermissionsError$inboundSchema,
} from "./permissions-error.js";

export type PermissionsErrorResponseData = {
  error?: PermissionsError | undefined;
};

export class PermissionsErrorResponse extends CldProvisioningError {
  error?: PermissionsError | undefined;

  /** The original data that was passed to this error instance. */
  data$: PermissionsErrorResponseData;

  constructor(
    err: PermissionsErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PermissionsErrorResponse";
  }
}

/** @internal */
export const PermissionsErrorResponse$inboundSchema: z.ZodMiniType<
  PermissionsErrorResponse,
  unknown
> = z.pipe(
  z.object({
    error: types.optional(PermissionsError$inboundSchema),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    return new PermissionsErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
