/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { CldProvisioningError } from "./cldprovisioningerror.js";
import {
  PermissionsError,
  PermissionsError$inboundSchema,
} from "./permissionserror.js";

export type PermissionsErrorResponseData = {
  error?: PermissionsError | undefined;
};

export class PermissionsErrorResponse extends CldProvisioningError {
  error?: PermissionsError | undefined;

  /** The original data that was passed to this error instance. */
  data$: PermissionsErrorResponseData;

  constructor(
    err: PermissionsErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PermissionsErrorResponse";
  }
}

/** @internal */
export const PermissionsErrorResponse$inboundSchema: z.ZodType<
  PermissionsErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: PermissionsError$inboundSchema.optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PermissionsErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
