/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * Additional contextual information about the error, which may include relevant data.
 */
export type Details = {};

export type PermissionsError = {
  /**
   * A classification of the error, indicating the general area or type of problem.
   */
  category?: string | undefined;
  /**
   * A specific error code that uniquely identifies the error condition.
   */
  code?: string | undefined;
  /**
   * A human-readable message providing a brief explanation of the error and its cause.
   */
  message?: string | undefined;
  /**
   * Additional contextual information about the error, which may include relevant data.
   */
  details?: Details | undefined;
};

/** @internal */
export const Details$inboundSchema: z.ZodMiniType<Details, unknown> = z.object(
  {},
);

export function detailsFromJSON(
  jsonString: string,
): SafeParseResult<Details, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Details$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Details' from JSON`,
  );
}

/** @internal */
export const PermissionsError$inboundSchema: z.ZodMiniType<
  PermissionsError,
  unknown
> = z.object({
  category: types.optional(types.string()),
  code: types.optional(types.string()),
  message: types.optional(types.string()),
  details: types.optional(z.lazy(() => Details$inboundSchema)),
});

export function permissionsErrorFromJSON(
  jsonString: string,
): SafeParseResult<PermissionsError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PermissionsError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PermissionsError' from JSON`,
  );
}
