/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ManagementTypeEnum,
  ManagementTypeEnum$inboundSchema,
} from "./managementtypeenum.js";
import {
  PermissionTypeEnum,
  PermissionTypeEnum$inboundSchema,
} from "./permissiontypeenum.js";
import { ScopeTypeEnum, ScopeTypeEnum$inboundSchema } from "./scopetypeenum.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
 *
 * @remarks
 * - The content type can be: `folder_id` or `collection_id`.
 * - When assigning the role, provide the instance, e.g. `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
 */
export type PolicyParameters = {};

export type PrincipalRolesData = {
  /**
   * The unique identifier of the role.
   */
  id: string;
  /**
   * The name of the role.
   */
  name: string;
  /**
   * A short description of the role.
   */
  description?: string | null | undefined;
  /**
   * Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
   */
  managementType: ManagementTypeEnum;
  /**
   * Specifies whether permissions apply globally or to specific content.
   */
  permissionType: PermissionTypeEnum;
  /**
   * Specifies where the role/policy is applied, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  /**
   * Returned only if the scope type is product environment. Can be "all" to represent all product environments or an ID of a specific product environment.
   */
  scopeId?: string | null | undefined;
  /**
   * For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
   *
   * @remarks
   * - The content type can be: `folder_id` or `collection_id`.
   * - When assigning the role, provide the instance, e.g. `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
   */
  policyParameters?: PolicyParameters | null | undefined;
  /**
   * Creation time of the policy in epoch time.
   */
  createdAt: number;
  /**
   * Last updated time of the policy in epoch time.
   */
  updatedAt: number;
};

/** @internal */
export const PolicyParameters$inboundSchema: z.ZodType<
  PolicyParameters,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function policyParametersFromJSON(
  jsonString: string,
): SafeParseResult<PolicyParameters, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PolicyParameters$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PolicyParameters' from JSON`,
  );
}

/** @internal */
export const PrincipalRolesData$inboundSchema: z.ZodType<
  PrincipalRolesData,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  management_type: ManagementTypeEnum$inboundSchema,
  permission_type: PermissionTypeEnum$inboundSchema,
  scope_type: ScopeTypeEnum$inboundSchema,
  scope_id: z.nullable(z.string()).optional(),
  policy_parameters: z.nullable(z.lazy(() => PolicyParameters$inboundSchema))
    .optional(),
  created_at: z.number().int(),
  updated_at: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "management_type": "managementType",
    "permission_type": "permissionType",
    "scope_type": "scopeType",
    "scope_id": "scopeId",
    "policy_parameters": "policyParameters",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function principalRolesDataFromJSON(
  jsonString: string,
): SafeParseResult<PrincipalRolesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrincipalRolesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrincipalRolesData' from JSON`,
  );
}
