/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  PrincipalRolesData,
  PrincipalRolesData$inboundSchema,
} from "./principal-roles-data.js";
import {
  PrincipalTypeEnum,
  PrincipalTypeEnum$inboundSchema,
} from "./principal-type-enum.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type PrincipalRolesInspectData = {
  /**
   * The type of principal.
   */
  type: PrincipalTypeEnum;
  /**
   * The unique identifier of the principal.
   */
  id: string;
  roles: Array<PrincipalRolesData>;
};

/** @internal */
export const PrincipalRolesInspectData$inboundSchema: z.ZodMiniType<
  PrincipalRolesInspectData,
  unknown
> = z.object({
  type: PrincipalTypeEnum$inboundSchema,
  id: types.string(),
  roles: z.array(PrincipalRolesData$inboundSchema),
});

export function principalRolesInspectDataFromJSON(
  jsonString: string,
): SafeParseResult<PrincipalRolesInspectData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrincipalRolesInspectData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrincipalRolesInspectData' from JSON`,
  );
}
