/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 41bfb3cf06c3
 */

import * as z from "zod/v4-mini";
import {
  PrincipalTypeEnum,
  PrincipalTypeEnum$outboundSchema,
} from "./principal-type-enum.js";

export type Principal = {
  /**
   * The type of principal.
   */
  type: PrincipalTypeEnum;
  /**
   * The unique identifier of the principal.
   */
  id: string;
};

/** @internal */
export type Principal$Outbound = {
  type: string;
  id: string;
};

/** @internal */
export const Principal$outboundSchema: z.ZodMiniType<
  Principal$Outbound,
  Principal
> = z.object({
  type: PrincipalTypeEnum$outboundSchema,
  id: z.string(),
});

export function principalToJSON(principal: Principal): string {
  return JSON.stringify(Principal$outboundSchema.parse(principal));
}
