/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  PrincipalRolesInspectData,
  PrincipalRolesInspectData$inboundSchema,
} from "./principalrolesinspectdata.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type PrincipalRolesInspectResponseData = {
  principals?: Array<PrincipalRolesInspectData> | undefined;
};

export type PrincipalRolesInspectResponse = {
  data?: PrincipalRolesInspectResponseData | undefined;
  nextCursor?: string | undefined;
};

/** @internal */
export const PrincipalRolesInspectResponseData$inboundSchema: z.ZodType<
  PrincipalRolesInspectResponseData,
  z.ZodTypeDef,
  unknown
> = z.object({
  principals: z.array(PrincipalRolesInspectData$inboundSchema).optional(),
});

export function principalRolesInspectResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PrincipalRolesInspectResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrincipalRolesInspectResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrincipalRolesInspectResponseData' from JSON`,
  );
}

/** @internal */
export const PrincipalRolesInspectResponse$inboundSchema: z.ZodType<
  PrincipalRolesInspectResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PrincipalRolesInspectResponseData$inboundSchema)
    .optional(),
  next_cursor: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "next_cursor": "nextCursor",
  });
});

export function principalRolesInspectResponseFromJSON(
  jsonString: string,
): SafeParseResult<PrincipalRolesInspectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrincipalRolesInspectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrincipalRolesInspectResponse' from JSON`,
  );
}
