/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  PrincipalRolesData,
  PrincipalRolesData$inboundSchema,
} from "./principalrolesdata.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type PrincipalRolesResponse = {
  data?: Array<PrincipalRolesData> | undefined;
};

/** @internal */
export const PrincipalRolesResponse$inboundSchema: z.ZodType<
  PrincipalRolesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(PrincipalRolesData$inboundSchema).optional(),
});

export function principalRolesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PrincipalRolesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrincipalRolesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrincipalRolesResponse' from JSON`,
  );
}
