/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  PrincipalResponseData,
  PrincipalResponseData$inboundSchema,
} from "./principalresponsedata.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type PrincipalsResponse = {
  /**
   * An array of principals.
   */
  data?: Array<PrincipalResponseData> | undefined;
};

/** @internal */
export const PrincipalsResponse$inboundSchema: z.ZodType<
  PrincipalsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(PrincipalResponseData$inboundSchema).optional(),
});

export function principalsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PrincipalsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrincipalsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrincipalsResponse' from JSON`,
  );
}
