/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  PrincipalRolesInspectData,
  PrincipalRolesInspectData$inboundSchema,
} from "./principal-roles-inspect-data.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type PrincipalRolesInspectResponseData = {
  principals?: Array<PrincipalRolesInspectData> | undefined;
};

export type PrincipalRolesInspectResponse = {
  data?: PrincipalRolesInspectResponseData | undefined;
  nextCursor?: string | undefined;
};

/** @internal */
export const PrincipalRolesInspectResponseData$inboundSchema: z.ZodMiniType<
  PrincipalRolesInspectResponseData,
  unknown
> = z.object({
  principals: types.optional(z.array(PrincipalRolesInspectData$inboundSchema)),
});

export function principalRolesInspectResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<PrincipalRolesInspectResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrincipalRolesInspectResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrincipalRolesInspectResponseData' from JSON`,
  );
}

/** @internal */
export const PrincipalRolesInspectResponse$inboundSchema: z.ZodMiniType<
  PrincipalRolesInspectResponse,
  unknown
> = z.pipe(
  z.object({
    data: types.optional(
      z.lazy(() => PrincipalRolesInspectResponseData$inboundSchema),
    ),
    next_cursor: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function principalRolesInspectResponseFromJSON(
  jsonString: string,
): SafeParseResult<PrincipalRolesInspectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrincipalRolesInspectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrincipalRolesInspectResponse' from JSON`,
  );
}
