/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  PrincipalRolesData,
  PrincipalRolesData$inboundSchema,
} from "./principal-roles-data.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type PrincipalRolesResponse = {
  data?: Array<PrincipalRolesData> | undefined;
};

/** @internal */
export const PrincipalRolesResponse$inboundSchema: z.ZodMiniType<
  PrincipalRolesResponse,
  unknown
> = z.object({
  data: types.optional(z.array(PrincipalRolesData$inboundSchema)),
});

export function principalRolesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PrincipalRolesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PrincipalRolesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PrincipalRolesResponse' from JSON`,
  );
}
