/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 75b179803a8c
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { ApiAccessKey, ApiAccessKey$inboundSchema } from "./api-access-key.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * Product Environment
 */
export type ProductEnvironment = {
  cloudName?: string | undefined;
  /**
   * The cloud name of the product environment.
   */
  name?: string | undefined;
  /**
   * Whether the product environment is enabled or disabled.
   */
  enabled?: boolean | undefined;
  /**
   * The ID of the product environment.
   */
  id?: string | undefined;
  /**
   * The list of the product environment's access keys.
   */
  apiAccessKeys?: Array<ApiAccessKey> | undefined;
  /**
   * The date when the product environment was created.
   */
  createdAt?: Date | undefined;
  /**
   * The date when the product environment was last updated.
   */
  updatedAt?: Date | undefined;
};

/** @internal */
export const ProductEnvironment$inboundSchema: z.ZodMiniType<
  ProductEnvironment,
  unknown
> = z.pipe(
  z.object({
    cloud_name: types.optional(types.string()),
    name: types.optional(types.string()),
    enabled: types.optional(types.boolean()),
    id: types.optional(types.string()),
    api_access_keys: types.optional(z.array(ApiAccessKey$inboundSchema)),
    created_at: types.optional(types.date()),
    updated_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cloud_name": "cloudName",
      "api_access_keys": "apiAccessKeys",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function productEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<ProductEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductEnvironment' from JSON`,
  );
}
