/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 5764320cdadf
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Custom attributes associated with the product environment (optional).
 */
export type CustomAttributes = {};

export type ProductEnvironmentRequest = {
  /**
   * The display name for the product environment.
   */
  name: string;
  /**
   * The Cloudinary cloud name (optional, default is auto-generated).
   */
  cloudName?: string | undefined;
  /**
   * The ID of another product environment to copy settings from (optional).
   */
  baseSubAccountId?: string | undefined;
  /**
   * Custom attributes associated with the product environment (optional).
   */
  customAttributes?: CustomAttributes | undefined;
};

/** @internal */
export type CustomAttributes$Outbound = {};

/** @internal */
export const CustomAttributes$outboundSchema: z.ZodMiniType<
  CustomAttributes$Outbound,
  CustomAttributes
> = z.object({});

export function customAttributesToJSON(
  customAttributes: CustomAttributes,
): string {
  return JSON.stringify(
    CustomAttributes$outboundSchema.parse(customAttributes),
  );
}

/** @internal */
export type ProductEnvironmentRequest$Outbound = {
  name: string;
  cloud_name?: string | undefined;
  base_sub_account_id?: string | undefined;
  custom_attributes?: CustomAttributes$Outbound | undefined;
};

/** @internal */
export const ProductEnvironmentRequest$outboundSchema: z.ZodMiniType<
  ProductEnvironmentRequest$Outbound,
  ProductEnvironmentRequest
> = z.pipe(
  z.object({
    name: z.string(),
    cloudName: z.optional(z.string()),
    baseSubAccountId: z.optional(z.string()),
    customAttributes: z.optional(z.lazy(() => CustomAttributes$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      cloudName: "cloud_name",
      baseSubAccountId: "base_sub_account_id",
      customAttributes: "custom_attributes",
    });
  }),
);

export function productEnvironmentRequestToJSON(
  productEnvironmentRequest: ProductEnvironmentRequest,
): string {
  return JSON.stringify(
    ProductEnvironmentRequest$outboundSchema.parse(productEnvironmentRequest),
  );
}
