/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Custom attributes associated with the product environment (optional).
 */
export type CustomAttributes = {};

export type ProductEnvironmentRequest = {
  /**
   * The display name for the product environment.
   */
  name: string;
  /**
   * The Cloudinary cloud name (optional, default is auto-generated).
   */
  cloudName?: string | undefined;
  /**
   * The ID of another product environment to copy settings from (optional).
   */
  baseSubAccountId?: string | undefined;
  /**
   * Custom attributes associated with the product environment (optional).
   */
  customAttributes?: CustomAttributes | undefined;
};

/** @internal */
export type CustomAttributes$Outbound = {};

/** @internal */
export const CustomAttributes$outboundSchema: z.ZodType<
  CustomAttributes$Outbound,
  z.ZodTypeDef,
  CustomAttributes
> = z.object({});

export function customAttributesToJSON(
  customAttributes: CustomAttributes,
): string {
  return JSON.stringify(
    CustomAttributes$outboundSchema.parse(customAttributes),
  );
}

/** @internal */
export type ProductEnvironmentRequest$Outbound = {
  name: string;
  cloud_name?: string | undefined;
  base_sub_account_id?: string | undefined;
  custom_attributes?: CustomAttributes$Outbound | undefined;
};

/** @internal */
export const ProductEnvironmentRequest$outboundSchema: z.ZodType<
  ProductEnvironmentRequest$Outbound,
  z.ZodTypeDef,
  ProductEnvironmentRequest
> = z.object({
  name: z.string(),
  cloudName: z.string().optional(),
  baseSubAccountId: z.string().optional(),
  customAttributes: z.lazy(() => CustomAttributes$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    cloudName: "cloud_name",
    baseSubAccountId: "base_sub_account_id",
    customAttributes: "custom_attributes",
  });
});

export function productEnvironmentRequestToJSON(
  productEnvironmentRequest: ProductEnvironmentRequest,
): string {
  return JSON.stringify(
    ProductEnvironmentRequest$outboundSchema.parse(productEnvironmentRequest),
  );
}
