/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 806ff0a6f66d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Custom attributes associated with the product environment.
 */
export type ProductEnvironmentUpdateRequestCustomAttributes = {};

export type ProductEnvironmentUpdateRequest = {
  /**
   * The display name for the product environment.
   */
  name?: string | undefined;
  /**
   * The Cloudinary cloud name. An error is returned if the requested name already exists.
   *
   * @remarks
   * **Note**: Can only be changed for accounts with fewer than 1000 images.
   */
  cloudName?: string | undefined;
  /**
   * Custom attributes associated with the product environment.
   */
  customAttributes?:
    | ProductEnvironmentUpdateRequestCustomAttributes
    | undefined;
  /**
   * Whether the product environment is enabled. **Default**: true.
   *
   * @remarks
   */
  enabled?: boolean | undefined;
};

/** @internal */
export type ProductEnvironmentUpdateRequestCustomAttributes$Outbound = {};

/** @internal */
export const ProductEnvironmentUpdateRequestCustomAttributes$outboundSchema:
  z.ZodMiniType<
    ProductEnvironmentUpdateRequestCustomAttributes$Outbound,
    ProductEnvironmentUpdateRequestCustomAttributes
  > = z.object({});

export function productEnvironmentUpdateRequestCustomAttributesToJSON(
  productEnvironmentUpdateRequestCustomAttributes:
    ProductEnvironmentUpdateRequestCustomAttributes,
): string {
  return JSON.stringify(
    ProductEnvironmentUpdateRequestCustomAttributes$outboundSchema.parse(
      productEnvironmentUpdateRequestCustomAttributes,
    ),
  );
}

/** @internal */
export type ProductEnvironmentUpdateRequest$Outbound = {
  name?: string | undefined;
  cloud_name?: string | undefined;
  custom_attributes?:
    | ProductEnvironmentUpdateRequestCustomAttributes$Outbound
    | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const ProductEnvironmentUpdateRequest$outboundSchema: z.ZodMiniType<
  ProductEnvironmentUpdateRequest$Outbound,
  ProductEnvironmentUpdateRequest
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    cloudName: z.optional(z.string()),
    customAttributes: z.optional(z.lazy(() =>
      ProductEnvironmentUpdateRequestCustomAttributes$outboundSchema
    )),
    enabled: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cloudName: "cloud_name",
      customAttributes: "custom_attributes",
    });
  }),
);

export function productEnvironmentUpdateRequestToJSON(
  productEnvironmentUpdateRequest: ProductEnvironmentUpdateRequest,
): string {
  return JSON.stringify(
    ProductEnvironmentUpdateRequest$outboundSchema.parse(
      productEnvironmentUpdateRequest,
    ),
  );
}
