/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ProductEnvironment,
  ProductEnvironment$inboundSchema,
} from "./productenvironment.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type ProductEnvironmentsResponse = {
  subAccounts?: Array<ProductEnvironment> | undefined;
};

/** @internal */
export const ProductEnvironmentsResponse$inboundSchema: z.ZodType<
  ProductEnvironmentsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  sub_accounts: z.array(ProductEnvironment$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "sub_accounts": "subAccounts",
  });
});

export function productEnvironmentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ProductEnvironmentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductEnvironmentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductEnvironmentsResponse' from JSON`,
  );
}
