/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { ApiAccessKey, ApiAccessKey$inboundSchema } from "./apiaccesskey.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * Product Environment
 */
export type ProductEnvironment = {
  cloudName?: string | undefined;
  /**
   * The cloud name of the product environment.
   */
  name?: string | undefined;
  /**
   * Whether the product environment is enabled or disabled.
   */
  enabled?: boolean | undefined;
  /**
   * The ID of the product environment.
   */
  id?: string | undefined;
  /**
   * The list of the product environment's access keys.
   */
  apiAccessKeys?: Array<ApiAccessKey> | undefined;
  /**
   * The date when the product environment was created.
   */
  createdAt?: Date | undefined;
  /**
   * The date when the product environment was last updated.
   */
  updatedAt?: Date | undefined;
};

/** @internal */
export const ProductEnvironment$inboundSchema: z.ZodType<
  ProductEnvironment,
  z.ZodTypeDef,
  unknown
> = z.object({
  cloud_name: z.string().optional(),
  name: z.string().optional(),
  enabled: z.boolean().optional(),
  id: z.string().optional(),
  api_access_keys: z.array(ApiAccessKey$inboundSchema).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
    "api_access_keys": "apiAccessKeys",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function productEnvironmentFromJSON(
  jsonString: string,
): SafeParseResult<ProductEnvironment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProductEnvironment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProductEnvironment' from JSON`,
  );
}
