/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  RoleResponseData,
  RoleResponseData$inboundSchema,
} from "./role-response-data.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type RolesResponse = {
  /**
   * An array of roles.
   */
  data?: Array<RoleResponseData> | undefined;
};

/** @internal */
export const RolesResponse$inboundSchema: z.ZodMiniType<
  RolesResponse,
  unknown
> = z.object({
  data: types.optional(z.array(RoleResponseData$inboundSchema)),
});

export function rolesResponseFromJSON(
  jsonString: string,
): SafeParseResult<RolesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RolesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RolesResponse' from JSON`,
  );
}
