/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

/**
 * Defines the content instance that the role applies to. Specify the content type (`folder_id` or `collection_id`) and its corresponding ID. For example, `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
 */
export type RoleToManagePolicyParameters = {};

export type RoleToManage = {
  /**
   * The unique identifier of the role you want to assign.
   */
  id: string;
  /**
   * The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is "prodenv".
   */
  scopeId?: string | undefined;
  /**
   * Defines the content instance that the role applies to. Specify the content type (`folder_id` or `collection_id`) and its corresponding ID. For example, `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
   */
  policyParameters?: RoleToManagePolicyParameters | undefined;
};

/** @internal */
export type RoleToManagePolicyParameters$Outbound = {};

/** @internal */
export const RoleToManagePolicyParameters$outboundSchema: z.ZodMiniType<
  RoleToManagePolicyParameters$Outbound,
  RoleToManagePolicyParameters
> = z.object({});

export function roleToManagePolicyParametersToJSON(
  roleToManagePolicyParameters: RoleToManagePolicyParameters,
): string {
  return JSON.stringify(
    RoleToManagePolicyParameters$outboundSchema.parse(
      roleToManagePolicyParameters,
    ),
  );
}

/** @internal */
export type RoleToManage$Outbound = {
  id: string;
  scope_id?: string | undefined;
  policy_parameters?: RoleToManagePolicyParameters$Outbound | undefined;
};

/** @internal */
export const RoleToManage$outboundSchema: z.ZodMiniType<
  RoleToManage$Outbound,
  RoleToManage
> = z.pipe(
  z.object({
    id: z.string(),
    scopeId: z.optional(z.string()),
    policyParameters: z.optional(
      z.lazy(() => RoleToManagePolicyParameters$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      scopeId: "scope_id",
      policyParameters: "policy_parameters",
    });
  }),
);

export function roleToManageToJSON(roleToManage: RoleToManage): string {
  return JSON.stringify(RoleToManage$outboundSchema.parse(roleToManage));
}
