/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: a1c825c45305
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ManagementTypeEnum,
  ManagementTypeEnum$inboundSchema,
} from "./management-type-enum.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$inboundSchema,
} from "./scope-type-enum.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type RoleResponseData = {
  /**
   * The unique identifier of the role.
   */
  id: string;
  /**
   * The name of the role.
   */
  name: string;
  /**
   * A short description of the role.
   */
  description?: string | null | undefined;
  /**
   * Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
   */
  managementType: ManagementTypeEnum;
  /**
   * Specifies whether the permission applies globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
   *
   * @remarks
   *
   *     - global
   *
   *     - content
   */
  permissionType: string;
  /**
   * For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
   *
   * @remarks
   * - The content type can be: `folder_id` or `collection_id`.
   * - When assigning the role, provide the instance, e.g. `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
   */
  policyParameters?: Array<string> | undefined;
  /**
   * Specifies where the role/policy is applied, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  /**
   * The permission policy creation timestamp in epoch time.
   */
  createdAt: number;
  /**
   * The permission policy last updated timestamp in epoch time.
   */
  updatedAt: number;
};

/** @internal */
export const RoleResponseData$inboundSchema: z.ZodMiniType<
  RoleResponseData,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    description: z.optional(z.nullable(types.string())),
    management_type: ManagementTypeEnum$inboundSchema,
    permission_type: types.string(),
    policy_parameters: types.optional(z.array(types.string())),
    scope_type: ScopeTypeEnum$inboundSchema,
    created_at: types.number(),
    updated_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "management_type": "managementType",
      "permission_type": "permissionType",
      "policy_parameters": "policyParameters",
      "scope_type": "scopeType",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function roleResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<RoleResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoleResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoleResponseData' from JSON`,
  );
}
