/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type Role = {
  /**
   * The name of the role.
   */
  name: string;
  /**
   * A short description of the role.
   */
  description?: string | null | undefined;
  /**
   * A list of system permission policy IDs to be included in the role.
   *
   * @remarks
   *
   * **Tip:** Get the list of all available predefined policies using the [Get system policies](#tag/policies/get/policies) method.
   */
  systemPolicyIds?: Array<string> | undefined;
};

/** @internal */
export type Role$Outbound = {
  name: string;
  description?: string | null | undefined;
  system_policy_ids?: Array<string> | undefined;
};

/** @internal */
export const Role$outboundSchema: z.ZodMiniType<Role$Outbound, Role> = z.pipe(
  z.object({
    name: z.string(),
    description: z.optional(z.nullable(z.string())),
    systemPolicyIds: z.optional(z.array(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      systemPolicyIds: "system_policy_ids",
    });
  }),
);

export function roleToJSON(role: Role): string {
  return JSON.stringify(Role$outboundSchema.parse(role));
}
