/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ManagementTypeEnum,
  ManagementTypeEnum$inboundSchema,
} from "./managementtypeenum.js";
import { ScopeTypeEnum, ScopeTypeEnum$inboundSchema } from "./scopetypeenum.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  SystemPolicyResponseData,
  SystemPolicyResponseData$inboundSchema,
} from "./systempolicyresponsedata.js";

export type RoleResponseData1 = {
  policies?: Array<SystemPolicyResponseData> | undefined;
  /**
   * The unique identifier of the role.
   */
  id: string;
  /**
   * The name of the role.
   */
  name: string;
  /**
   * A short description of the role.
   */
  description?: string | null | undefined;
  /**
   * Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`).
   */
  managementType: ManagementTypeEnum;
  /**
   * Specifies whether the permission applies globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
   *
   * @remarks
   *
   *     - global
   *
   *     - content
   */
  permissionType: string;
  /**
   * For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
   *
   * @remarks
   * - The content type can be: `folder_id` or `collection_id`.
   * - When assigning the role, provide the instance, e.g. `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
   */
  policyParameters?: Array<string> | undefined;
  /**
   * Specifies where the role/policy is applied, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  /**
   * The permission policy creation timestamp in epoch time.
   */
  createdAt: number;
  /**
   * The permission policy last updated timestamp in epoch time.
   */
  updatedAt: number;
};

export type RoleResponse = {
  data?: RoleResponseData1 | undefined;
};

/** @internal */
export const RoleResponseData1$inboundSchema: z.ZodType<
  RoleResponseData1,
  z.ZodTypeDef,
  unknown
> = z.object({
  policies: z.array(SystemPolicyResponseData$inboundSchema).optional(),
  id: z.string(),
  name: z.string(),
  description: z.nullable(z.string()).optional(),
  management_type: ManagementTypeEnum$inboundSchema,
  permission_type: z.string(),
  policy_parameters: z.array(z.string()).optional(),
  scope_type: ScopeTypeEnum$inboundSchema,
  created_at: z.number().int(),
  updated_at: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "management_type": "managementType",
    "permission_type": "permissionType",
    "policy_parameters": "policyParameters",
    "scope_type": "scopeType",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function roleResponseData1FromJSON(
  jsonString: string,
): SafeParseResult<RoleResponseData1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoleResponseData1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoleResponseData1' from JSON`,
  );
}

/** @internal */
export const RoleResponse$inboundSchema: z.ZodType<
  RoleResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => RoleResponseData1$inboundSchema).optional(),
});

export function roleResponseFromJSON(
  jsonString: string,
): SafeParseResult<RoleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoleResponse' from JSON`,
  );
}
