/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";

/**
 * Specifies where the role/policy is applied, either at the account level or within product environments.
 */
export const ScopeTypeEnum = {
  Account: "account",
  Prodenv: "prodenv",
} as const;
/**
 * Specifies where the role/policy is applied, either at the account level or within product environments.
 */
export type ScopeTypeEnum = OpenEnum<typeof ScopeTypeEnum>;

/** @internal */
export const ScopeTypeEnum$inboundSchema: z.ZodMiniType<
  ScopeTypeEnum,
  unknown
> = openEnums.inboundSchema(ScopeTypeEnum);
/** @internal */
export const ScopeTypeEnum$outboundSchema: z.ZodMiniType<
  string,
  ScopeTypeEnum
> = openEnums.outboundSchema(ScopeTypeEnum);
