/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: d90c6c784ca5
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";

export type Security = {
  provisioningApiKey?: string | undefined;
  provisioningApiSecret?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  provisioning_api_key?: string | undefined;
  provisioning_api_secret?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodMiniType<
  Security$Outbound,
  Security
> = z.pipe(
  z.object({
    provisioningApiKey: z.optional(z.string()),
    provisioningApiSecret: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      provisioningApiKey: "provisioning_api_key",
      provisioningApiSecret: "provisioning_api_secret",
    });
  }),
);

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
