/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type Security = {
  provisioningApiKey?: string | undefined;
  provisioningApiSecret?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  provisioning_api_key?: string | undefined;
  provisioning_api_secret?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  provisioningApiKey: z.string().optional(),
  provisioningApiSecret: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    provisioningApiKey: "provisioning_api_key",
    provisioningApiSecret: "provisioning_api_secret",
  });
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
