/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * Product environment (sub-account) summary.
 */
export type SubAccountSummary = {
  /**
   * The product environment's ID.
   */
  id?: string | undefined;
  /**
   * The product environment's name.
   */
  name?: string | undefined;
  /**
   * The product environment's description.
   */
  description?: string | undefined;
  /**
   * The Cloudinary cloud name of the product environment.
   */
  cloudName?: string | undefined;
  /**
   * Whether the product environment is enabled.
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const SubAccountSummary$inboundSchema: z.ZodMiniType<
  SubAccountSummary,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
    description: types.optional(types.string()),
    cloud_name: types.optional(types.string()),
    enabled: types.optional(types.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "cloud_name": "cloudName",
    });
  }),
);

export function subAccountSummaryFromJSON(
  jsonString: string,
): SafeParseResult<SubAccountSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubAccountSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubAccountSummary' from JSON`,
  );
}
