/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * Product environment (sub-account) summary.
 */
export type SubAccountSummary = {
  /**
   * The product environment's ID.
   */
  id?: string | undefined;
  /**
   * The product environment's name.
   */
  name?: string | undefined;
  /**
   * The product environment's description.
   */
  description?: string | undefined;
  /**
   * The Cloudinary cloud name of the product environment.
   */
  cloudName?: string | undefined;
  /**
   * Whether the product environment is enabled.
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const SubAccountSummary$inboundSchema: z.ZodType<
  SubAccountSummary,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  cloud_name: z.string().optional(),
  enabled: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "cloud_name": "cloudName",
  });
});

export function subAccountSummaryFromJSON(
  jsonString: string,
): SafeParseResult<SubAccountSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubAccountSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubAccountSummary' from JSON`,
  );
}
