/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: bdfe5c6631a3
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type Catalog = {};

export type SystemRolesAndPoliciesCatalogResponse = {
  catalog: Catalog;
};

/** @internal */
export const Catalog$inboundSchema: z.ZodMiniType<Catalog, unknown> = z.object(
  {},
);

export function catalogFromJSON(
  jsonString: string,
): SafeParseResult<Catalog, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Catalog$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Catalog' from JSON`,
  );
}

/** @internal */
export const SystemRolesAndPoliciesCatalogResponse$inboundSchema: z.ZodMiniType<
  SystemRolesAndPoliciesCatalogResponse,
  unknown
> = z.object({
  catalog: z.lazy(() => Catalog$inboundSchema),
});

export function systemRolesAndPoliciesCatalogResponseFromJSON(
  jsonString: string,
): SafeParseResult<SystemRolesAndPoliciesCatalogResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      SystemRolesAndPoliciesCatalogResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SystemRolesAndPoliciesCatalogResponse' from JSON`,
  );
}
