/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ScopeTypeEnum,
  ScopeTypeEnum$inboundSchema,
} from "./scope-type-enum.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type SystemPolicyResponseData = {
  /**
   * The unique identifier of the policy.
   */
  id: string;
  /**
   * The name of the policy
   */
  name: string;
  /**
   * A short description of the policy.
   */
  description?: string | null | undefined;
  /**
   * Specifies where the role/policy is applied, either at the account level or within product environments.
   */
  scopeType: ScopeTypeEnum;
  /**
   * Specifies whether the permission applies globally across all resources or contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID "fg3841spr").
   *
   * @remarks
   *
   *     - global
   *
   *     - content
   */
  permissionType?: string | undefined;
  /**
   * A Cedar policy that permits or forbids a certain action on a certain element to a principal (user, group, or API key).
   */
  policyStatement: string;
  /**
   * For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
   *
   * @remarks
   * - The content type can be: `folder_id` or `collection_id`.
   * - When assigning the role, provide the instance, e.g. `{"folder_id":"asdfjkl12347890"}`. This specification is passed to the `policy_statement` (Cedar).
   */
  policyParameters?: Array<string> | undefined;
  /**
   * The category of the policy.
   */
  category?: string | undefined;
  /**
   * The sub-category of the policy.
   */
  subCategory?: string | undefined;
  /**
   * Creation time of the policy in epoch time.
   */
  createdAt: number;
  /**
   * Last update time of the policy in epoch time.
   */
  updatedAt: number;
};

/** @internal */
export const SystemPolicyResponseData$inboundSchema: z.ZodMiniType<
  SystemPolicyResponseData,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    name: types.string(),
    description: z.optional(z.nullable(types.string())),
    scope_type: ScopeTypeEnum$inboundSchema,
    permission_type: types.optional(types.string()),
    policy_statement: types.string(),
    policy_parameters: types.optional(z.array(types.string())),
    category: types.optional(types.string()),
    sub_category: types.optional(types.string()),
    created_at: types.number(),
    updated_at: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "scope_type": "scopeType",
      "permission_type": "permissionType",
      "policy_statement": "policyStatement",
      "policy_parameters": "policyParameters",
      "sub_category": "subCategory",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function systemPolicyResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<SystemPolicyResponseData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SystemPolicyResponseData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SystemPolicyResponseData' from JSON`,
  );
}
