/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6627c10f4e4d
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  SystemPolicyResponseData,
  SystemPolicyResponseData$inboundSchema,
} from "./system-policy-response-data.js";

export type SystemPoliciesResponse = {
  /**
   * An array of system policies.
   */
  data?: Array<SystemPolicyResponseData> | undefined;
  /**
   * When a request has more results to return, the next_cursor value is returned as part of the response. You can then specify this value as the cursor parameter of a following request.
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const SystemPoliciesResponse$inboundSchema: z.ZodMiniType<
  SystemPoliciesResponse,
  unknown
> = z.pipe(
  z.object({
    data: types.optional(z.array(SystemPolicyResponseData$inboundSchema)),
    next_cursor: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function systemPoliciesResponseFromJSON(
  jsonString: string,
): SafeParseResult<SystemPoliciesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SystemPoliciesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SystemPoliciesResponse' from JSON`,
  );
}
