/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { Role, Role$Outbound, Role$outboundSchema } from "./role.js";

export type UpdateRoleGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type UpdateRoleRequest = {
  /**
   * A unique identifier for the role.
   */
  roleId: string;
  /**
   * Role details
   */
  role: Role;
};

/** @internal */
export type UpdateRoleRequest$Outbound = {
  role_id: string;
  Role: Role$Outbound;
};

/** @internal */
export const UpdateRoleRequest$outboundSchema: z.ZodType<
  UpdateRoleRequest$Outbound,
  z.ZodTypeDef,
  UpdateRoleRequest
> = z.object({
  roleId: z.string(),
  role: Role$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    roleId: "role_id",
    role: "Role",
  });
});

export function updateRoleRequestToJSON(
  updateRoleRequest: UpdateRoleRequest,
): string {
  return JSON.stringify(
    UpdateRoleRequest$outboundSchema.parse(updateRoleRequest),
  );
}
