/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  AccessKeyUpdateRequest,
  AccessKeyUpdateRequest$Outbound,
  AccessKeyUpdateRequest$outboundSchema,
} from "./accesskeyupdaterequest.js";

export type UpdateAccessKeyGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type UpdateAccessKeyRequest = {
  /**
   * The ID of the product environment.
   */
  subAccountId: string;
  /**
   * The access key (api key).
   */
  key: string;
  /**
   * Access key details for update.
   */
  accessKeyUpdateRequest: AccessKeyUpdateRequest;
};

/** @internal */
export type UpdateAccessKeyRequest$Outbound = {
  sub_account_id: string;
  key: string;
  AccessKeyUpdateRequest: AccessKeyUpdateRequest$Outbound;
};

/** @internal */
export const UpdateAccessKeyRequest$outboundSchema: z.ZodType<
  UpdateAccessKeyRequest$Outbound,
  z.ZodTypeDef,
  UpdateAccessKeyRequest
> = z.object({
  subAccountId: z.string(),
  key: z.string(),
  accessKeyUpdateRequest: AccessKeyUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    subAccountId: "sub_account_id",
    accessKeyUpdateRequest: "AccessKeyUpdateRequest",
  });
});

export function updateAccessKeyRequestToJSON(
  updateAccessKeyRequest: UpdateAccessKeyRequest,
): string {
  return JSON.stringify(
    UpdateAccessKeyRequest$outboundSchema.parse(updateAccessKeyRequest),
  );
}
