/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  OperationEnum,
  OperationEnum$outboundSchema,
} from "./operationenum.js";
import {
  UpdateRolePrincipal,
  UpdateRolePrincipal$Outbound,
  UpdateRolePrincipal$outboundSchema,
} from "./updateroleprincipal.js";

export type UpdateRolePrincipalsRequest = {
  /**
   * Specifies the operation to perform. Use `add` to associate or `remove` to disassociate.
   */
  operation?: OperationEnum | undefined;
  principals?: Array<UpdateRolePrincipal> | undefined;
};

/** @internal */
export type UpdateRolePrincipalsRequest$Outbound = {
  operation?: string | undefined;
  principals?: Array<UpdateRolePrincipal$Outbound> | undefined;
};

/** @internal */
export const UpdateRolePrincipalsRequest$outboundSchema: z.ZodType<
  UpdateRolePrincipalsRequest$Outbound,
  z.ZodTypeDef,
  UpdateRolePrincipalsRequest
> = z.object({
  operation: OperationEnum$outboundSchema.optional(),
  principals: z.array(UpdateRolePrincipal$outboundSchema).optional(),
});

export function updateRolePrincipalsRequestToJSON(
  updateRolePrincipalsRequest: UpdateRolePrincipalsRequest,
): string {
  return JSON.stringify(
    UpdateRolePrincipalsRequest$outboundSchema.parse(
      updateRolePrincipalsRequest,
    ),
  );
}
