/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 1787bd43f938
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  UpdateCustomPolicy,
  UpdateCustomPolicy$Outbound,
  UpdateCustomPolicy$outboundSchema,
} from "./update-custom-policy.js";

export type UpdateCustomPolicyGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type UpdateCustomPolicyRequest = {
  /**
   * A unique identifier for the custom permission policy.
   */
  policyId: string;
  /**
   * Policy details
   */
  updateCustomPolicy: UpdateCustomPolicy;
};

/** @internal */
export type UpdateCustomPolicyRequest$Outbound = {
  policy_id: string;
  UpdateCustomPolicy: UpdateCustomPolicy$Outbound;
};

/** @internal */
export const UpdateCustomPolicyRequest$outboundSchema: z.ZodMiniType<
  UpdateCustomPolicyRequest$Outbound,
  UpdateCustomPolicyRequest
> = z.pipe(
  z.object({
    policyId: z.string(),
    updateCustomPolicy: UpdateCustomPolicy$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      policyId: "policy_id",
      updateCustomPolicy: "UpdateCustomPolicy",
    });
  }),
);

export function updateCustomPolicyRequestToJSON(
  updateCustomPolicyRequest: UpdateCustomPolicyRequest,
): string {
  return JSON.stringify(
    UpdateCustomPolicyRequest$outboundSchema.parse(updateCustomPolicyRequest),
  );
}
