/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4cabb2aa96a3
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  UpdateRolePrincipalsRequest,
  UpdateRolePrincipalsRequest$Outbound,
  UpdateRolePrincipalsRequest$outboundSchema,
} from "./update-role-principals-request.js";

export type UpdateRolePrincipalsGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type UpdateRolePrincipalsRequest1 = {
  /**
   * A unique identifier for the role.
   */
  roleId: string;
  /**
   * Principals details.
   */
  updateRolePrincipalsRequest: UpdateRolePrincipalsRequest;
};

/** @internal */
export type UpdateRolePrincipalsRequest1$Outbound = {
  role_id: string;
  UpdateRolePrincipalsRequest: UpdateRolePrincipalsRequest$Outbound;
};

/** @internal */
export const UpdateRolePrincipalsRequest1$outboundSchema: z.ZodMiniType<
  UpdateRolePrincipalsRequest1$Outbound,
  UpdateRolePrincipalsRequest1
> = z.pipe(
  z.object({
    roleId: z.string(),
    updateRolePrincipalsRequest: UpdateRolePrincipalsRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      roleId: "role_id",
      updateRolePrincipalsRequest: "UpdateRolePrincipalsRequest",
    });
  }),
);

export function updateRolePrincipalsRequest1ToJSON(
  updateRolePrincipalsRequest1: UpdateRolePrincipalsRequest1,
): string {
  return JSON.stringify(
    UpdateRolePrincipalsRequest1$outboundSchema.parse(
      updateRolePrincipalsRequest1,
    ),
  );
}
