/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  UserGroupRequest,
  UserGroupRequest$Outbound,
  UserGroupRequest$outboundSchema,
} from "./user-group-request.js";

export type UpdateUserGroupGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type UpdateUserGroupRequest = {
  /**
   * The ID of the user group.
   */
  groupId: string;
  /**
   * User group details to update.
   */
  userGroupRequest: UserGroupRequest;
};

/** @internal */
export type UpdateUserGroupRequest$Outbound = {
  group_id: string;
  UserGroupRequest: UserGroupRequest$Outbound;
};

/** @internal */
export const UpdateUserGroupRequest$outboundSchema: z.ZodMiniType<
  UpdateUserGroupRequest$Outbound,
  UpdateUserGroupRequest
> = z.pipe(
  z.object({
    groupId: z.string(),
    userGroupRequest: UserGroupRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      groupId: "group_id",
      userGroupRequest: "UserGroupRequest",
    });
  }),
);

export function updateUserGroupRequestToJSON(
  updateUserGroupRequest: UpdateUserGroupRequest,
): string {
  return JSON.stringify(
    UpdateUserGroupRequest$outboundSchema.parse(updateUserGroupRequest),
  );
}
