/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  OperationEnum,
  OperationEnum$outboundSchema,
} from "./operation-enum.js";
import {
  UpdateRolePrincipal,
  UpdateRolePrincipal$Outbound,
  UpdateRolePrincipal$outboundSchema,
} from "./update-role-principal.js";

export type UpdateRolePrincipalsRequest = {
  /**
   * Specifies the operation to perform. Use `add` to associate or `remove` to disassociate.
   */
  operation?: OperationEnum | undefined;
  principals?: Array<UpdateRolePrincipal> | undefined;
};

/** @internal */
export type UpdateRolePrincipalsRequest$Outbound = {
  operation?: string | undefined;
  principals?: Array<UpdateRolePrincipal$Outbound> | undefined;
};

/** @internal */
export const UpdateRolePrincipalsRequest$outboundSchema: z.ZodMiniType<
  UpdateRolePrincipalsRequest$Outbound,
  UpdateRolePrincipalsRequest
> = z.object({
  operation: z.optional(OperationEnum$outboundSchema),
  principals: z.optional(z.array(UpdateRolePrincipal$outboundSchema)),
});

export function updateRolePrincipalsRequestToJSON(
  updateRolePrincipalsRequest: UpdateRolePrincipalsRequest,
): string {
  return JSON.stringify(
    UpdateRolePrincipalsRequest$outboundSchema.parse(
      updateRolePrincipalsRequest,
    ),
  );
}
