/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import {
  ProductEnvironmentUpdateRequest,
  ProductEnvironmentUpdateRequest$Outbound,
  ProductEnvironmentUpdateRequest$outboundSchema,
} from "./productenvironmentupdaterequest.js";

export type UpdateProductEnvironmentGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type UpdateProductEnvironmentRequest = {
  /**
   * The ID of the product environment.
   */
  subAccountId: string;
  /**
   * Product environment details to update.
   */
  productEnvironmentUpdateRequest: ProductEnvironmentUpdateRequest;
};

/** @internal */
export type UpdateProductEnvironmentRequest$Outbound = {
  sub_account_id: string;
  ProductEnvironmentUpdateRequest: ProductEnvironmentUpdateRequest$Outbound;
};

/** @internal */
export const UpdateProductEnvironmentRequest$outboundSchema: z.ZodType<
  UpdateProductEnvironmentRequest$Outbound,
  z.ZodTypeDef,
  UpdateProductEnvironmentRequest
> = z.object({
  subAccountId: z.string(),
  productEnvironmentUpdateRequest:
    ProductEnvironmentUpdateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    subAccountId: "sub_account_id",
    productEnvironmentUpdateRequest: "ProductEnvironmentUpdateRequest",
  });
});

export function updateProductEnvironmentRequestToJSON(
  updateProductEnvironmentRequest: UpdateProductEnvironmentRequest,
): string {
  return JSON.stringify(
    UpdateProductEnvironmentRequest$outboundSchema.parse(
      updateProductEnvironmentRequest,
    ),
  );
}
