/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 6d5ac46ef4d6
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import {
  UserRequest,
  UserRequest$Outbound,
  UserRequest$outboundSchema,
} from "./user-request.js";

export type UpdateUserGlobals = {
  /**
   * Account ID
   */
  accountId?: string | undefined;
};

export type UpdateUserRequest = {
  /**
   * The ID of the user.
   */
  userId: string;
  /**
   * User details to update.
   */
  userRequest: UserRequest;
};

/** @internal */
export type UpdateUserRequest$Outbound = {
  user_id: string;
  UserRequest: UserRequest$Outbound;
};

/** @internal */
export const UpdateUserRequest$outboundSchema: z.ZodMiniType<
  UpdateUserRequest$Outbound,
  UpdateUserRequest
> = z.pipe(
  z.object({
    userId: z.string(),
    userRequest: UserRequest$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      userId: "user_id",
      userRequest: "UserRequest",
    });
  }),
);

export function updateUserRequestToJSON(
  updateUserRequest: UpdateUserRequest,
): string {
  return JSON.stringify(
    UpdateUserRequest$outboundSchema.parse(updateUserRequest),
  );
}
