/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  OperationEnum,
  OperationEnum$outboundSchema,
} from "./operation-enum.js";
import {
  Principal,
  Principal$Outbound,
  Principal$outboundSchema,
} from "./principal.js";
import {
  RoleToManage,
  RoleToManage$Outbound,
  RoleToManage$outboundSchema,
} from "./role-to-manage.js";

export type UpdatePrincipalRolesRequest = {
  /**
   * Specifies the operation to perform. Use `add` to associate or `remove` to disassociate.
   */
  operation?: OperationEnum | undefined;
  principal?: Principal | undefined;
  roles?: Array<RoleToManage> | undefined;
};

/** @internal */
export type UpdatePrincipalRolesRequest$Outbound = {
  operation?: string | undefined;
  principal?: Principal$Outbound | undefined;
  roles?: Array<RoleToManage$Outbound> | undefined;
};

/** @internal */
export const UpdatePrincipalRolesRequest$outboundSchema: z.ZodMiniType<
  UpdatePrincipalRolesRequest$Outbound,
  UpdatePrincipalRolesRequest
> = z.object({
  operation: z.optional(OperationEnum$outboundSchema),
  principal: z.optional(Principal$outboundSchema),
  roles: z.optional(z.array(RoleToManage$outboundSchema)),
});

export function updatePrincipalRolesRequestToJSON(
  updatePrincipalRolesRequest: UpdatePrincipalRolesRequest,
): string {
  return JSON.stringify(
    UpdatePrincipalRolesRequest$outboundSchema.parse(
      updatePrincipalRolesRequest,
    ),
  );
}
