/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 102901783f49
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import { User, User$inboundSchema } from "./user.js";

export type UsersResponse = {
  users?: Array<User> | undefined;
};

/** @internal */
export const UsersResponse$inboundSchema: z.ZodMiniType<
  UsersResponse,
  unknown
> = z.object({
  users: types.optional(z.array(User$inboundSchema)),
});

export function usersResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsersResponse' from JSON`,
  );
}
