/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  UserGroupSummary,
  UserGroupSummary$inboundSchema,
} from "./usergroupsummary.js";

export type UserGroupsListResponse = {
  /**
   * A list of user groups that the user belongs to.
   */
  groups?: Array<UserGroupSummary> | undefined;
};

/** @internal */
export const UserGroupsListResponse$inboundSchema: z.ZodType<
  UserGroupsListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  groups: z.array(UserGroupSummary$inboundSchema).optional(),
});

export function userGroupsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<UserGroupsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGroupsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGroupsListResponse' from JSON`,
  );
}
