/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 4a37de716f51
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * User group user.
 */
export type UserGroupUser = {
  /**
   * The user's ID.
   */
  id?: string | undefined;
  /**
   * The user's name.
   */
  name?: string | undefined;
  /**
   * The user's email.
   */
  email?: string | undefined;
};

/** @internal */
export const UserGroupUser$inboundSchema: z.ZodMiniType<
  UserGroupUser,
  unknown
> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
  email: types.optional(types.string()),
});

export function userGroupUserFromJSON(
  jsonString: string,
): SafeParseResult<UserGroupUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGroupUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGroupUser' from JSON`,
  );
}
