/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 0c8006296319
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  UserGroupUser,
  UserGroupUser$inboundSchema,
} from "./user-group-user.js";

export type UserGroupUsersResponse = {
  /**
   * A list of user group users.
   */
  users?: Array<UserGroupUser> | undefined;
};

/** @internal */
export const UserGroupUsersResponse$inboundSchema: z.ZodMiniType<
  UserGroupUsersResponse,
  unknown
> = z.object({
  users: types.optional(z.array(UserGroupUser$inboundSchema)),
});

export function userGroupUsersResponseFromJSON(
  jsonString: string,
): SafeParseResult<UserGroupUsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGroupUsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGroupUsersResponse' from JSON`,
  );
}
