/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * User group summary.
 */
export type UserGroupSummary = {
  /**
   * The user group's ID.
   */
  id?: string | undefined;
  /**
   * The user group's name.
   */
  name?: string | undefined;
};

/** @internal */
export const UserGroupSummary$inboundSchema: z.ZodMiniType<
  UserGroupSummary,
  unknown
> = z.object({
  id: types.optional(types.string()),
  name: types.optional(types.string()),
});

export function userGroupSummaryFromJSON(
  jsonString: string,
): SafeParseResult<UserGroupSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGroupSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGroupSummary' from JSON`,
  );
}
