/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";

export type UserGroupRequest = {
  /**
   * The user group's name.
   */
  name?: string | undefined;
  /**
   * Whether to only return extended (true) or basic information about the group (false).
   *
   * @remarks
   * **Default**: false.
   */
  extendedDetails?: boolean | undefined;
};

/** @internal */
export type UserGroupRequest$Outbound = {
  name?: string | undefined;
  extended_details?: boolean | undefined;
};

/** @internal */
export const UserGroupRequest$outboundSchema: z.ZodType<
  UserGroupRequest$Outbound,
  z.ZodTypeDef,
  UserGroupRequest
> = z.object({
  name: z.string().optional(),
  extendedDetails: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    extendedDetails: "extended_details",
  });
});

export function userGroupRequestToJSON(
  userGroupRequest: UserGroupRequest,
): string {
  return JSON.stringify(
    UserGroupRequest$outboundSchema.parse(userGroupRequest),
  );
}
