/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 29542e94f068
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";
import {
  UserGroupSummary,
  UserGroupSummary$inboundSchema,
} from "./user-group-summary.js";

export type UserGroupsListResponse = {
  /**
   * A list of user groups that the user belongs to.
   */
  groups?: Array<UserGroupSummary> | undefined;
};

/** @internal */
export const UserGroupsListResponse$inboundSchema: z.ZodMiniType<
  UserGroupsListResponse,
  unknown
> = z.object({
  groups: types.optional(z.array(UserGroupSummary$inboundSchema)),
});

export function userGroupsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<UserGroupsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGroupsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGroupsListResponse' from JSON`,
  );
}
