/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

/**
 * User group user.
 */
export type UserGroupUser = {
  /**
   * The user's ID.
   */
  id?: string | undefined;
  /**
   * The user's name.
   */
  name?: string | undefined;
  /**
   * The user's email.
   */
  email?: string | undefined;
};

/** @internal */
export const UserGroupUser$inboundSchema: z.ZodType<
  UserGroupUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  email: z.string().optional(),
});

export function userGroupUserFromJSON(
  jsonString: string,
): SafeParseResult<UserGroupUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGroupUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGroupUser' from JSON`,
  );
}
