/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import { User, User$inboundSchema } from "./user.js";

export type UsersResponse = {
  users?: Array<User> | undefined;
};

/** @internal */
export const UsersResponse$inboundSchema: z.ZodType<
  UsersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  users: z.array(User$inboundSchema).optional(),
});

export function usersResponseFromJSON(
  jsonString: string,
): SafeParseResult<UsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UsersResponse' from JSON`,
  );
}
