/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import { UserGroup, UserGroup$inboundSchema } from "./usergroup.js";

export type UserGroupsResponse = {
  /**
   * A list of user groups.
   */
  userGroups?: Array<UserGroup> | undefined;
};

/** @internal */
export const UserGroupsResponse$inboundSchema: z.ZodType<
  UserGroupsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  user_groups: z.array(UserGroup$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "user_groups": "userGroups",
  });
});

export function userGroupsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UserGroupsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserGroupsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserGroupsResponse' from JSON`,
  );
}
