/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 3bf0cf37eb6b
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { ClosedEnum } from "../types/enums.js";

/**
 * The role to assign.
 */
export const UserRequestRole = {
  MasterAdmin: "master_admin",
  Admin: "admin",
  Billing: "billing",
  TechnicalAdmin: "technical_admin",
  Reports: "reports",
  MediaLibraryAdmin: "media_library_admin",
  MediaLibraryUser: "media_library_user",
} as const;
/**
 * The role to assign.
 */
export type UserRequestRole = ClosedEnum<typeof UserRequestRole>;

export type UserRequest = {
  /**
   * The user's name.
   */
  name?: string | undefined;
  /**
   * A unique email address, which serves as the login name and notification address.
   */
  email?: string | undefined;
  /**
   * The role to assign.
   */
  role?: UserRequestRole | undefined;
  /**
   * A list of product environment IDs that this user can access. Ignored if the role is `master_admin`.
   *
   * @remarks
   * **Default**: all product environments.
   */
  subAccountIds?: Array<string> | undefined;
  /**
   * Whether the user is enabled. **Default**: true.
   *
   * @remarks
   */
  enabled?: boolean | undefined;
};

/** @internal */
export const UserRequestRole$outboundSchema: z.ZodMiniEnum<
  typeof UserRequestRole
> = z.enum(UserRequestRole);

/** @internal */
export type UserRequest$Outbound = {
  name?: string | undefined;
  email?: string | undefined;
  role?: string | undefined;
  sub_account_ids?: Array<string> | undefined;
  enabled?: boolean | undefined;
};

/** @internal */
export const UserRequest$outboundSchema: z.ZodMiniType<
  UserRequest$Outbound,
  UserRequest
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    email: z.optional(z.string()),
    role: z.optional(UserRequestRole$outboundSchema),
    subAccountIds: z.optional(z.array(z.string())),
    enabled: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      subAccountIds: "sub_account_ids",
    });
  }),
);

export function userRequestToJSON(userRequest: UserRequest): string {
  return JSON.stringify(UserRequest$outboundSchema.parse(userRequest));
}
