/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./sdk-validation-error.js";

/**
 * The user's email preferences.
 */
export type EmailPreferences = {};

/**
 * User details.
 */
export type User = {
  /**
   * The user's ID.
   */
  id?: string | undefined;
  /**
   * The user's name.
   */
  name?: string | undefined;
  /**
   * The user's first name.
   */
  firstName?: string | undefined;
  /**
   * The user's last name.
   */
  lastName?: string | undefined;
  /**
   * The user's role.
   */
  role?: string | undefined;
  /**
   * The user's email.
   */
  email?: string | undefined;
  /**
   * Whether the user is pending.
   */
  pending?: boolean | undefined;
  /**
   * Whether the user is enabled.
   */
  enabled?: boolean | undefined;
  /**
   * The date when the user was created.
   */
  createdAt?: Date | undefined;
  /**
   * The date when the user was last updated.
   */
  updatedAt?: Date | undefined;
  /**
   * The date when the user was last logged in.
   */
  lastLogin?: Date | undefined;
  allSubAccounts?: boolean | undefined;
  /**
   * The list of authentication providers for the user.
   */
  providers?: Array<string> | undefined;
  /**
   * The user's email preferences.
   */
  emailPreferences?: EmailPreferences | undefined;
  /**
   * The account ID.
   */
  accountId?: string | undefined;
  /**
   * Whether two-factor authentication is enabled.
   */
  twoFactor?: boolean | undefined;
  /**
   * The user's status.
   */
  status?: string | undefined;
  /**
   * Whether the user is a root user.
   */
  root?: boolean | undefined;
  /**
   * The user's technical role.
   */
  technicalRole?: string | undefined;
  /**
   * The number of groups the user belongs to.
   */
  groupCount?: number | undefined;
  /**
   * The number of sub-accounts the user has access to.
   */
  subAccountCount?: number | undefined;
};

/** @internal */
export const EmailPreferences$inboundSchema: z.ZodMiniType<
  EmailPreferences,
  unknown
> = z.object({});

export function emailPreferencesFromJSON(
  jsonString: string,
): SafeParseResult<EmailPreferences, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailPreferences$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailPreferences' from JSON`,
  );
}

/** @internal */
export const User$inboundSchema: z.ZodMiniType<User, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    name: types.optional(types.string()),
    first_name: types.optional(types.string()),
    last_name: types.optional(types.string()),
    role: types.optional(types.string()),
    email: types.optional(types.string()),
    pending: types.optional(types.boolean()),
    enabled: types.optional(types.boolean()),
    created_at: types.optional(types.date()),
    updated_at: types.optional(types.date()),
    last_login: types.optional(types.date()),
    all_sub_accounts: types.optional(types.boolean()),
    providers: types.optional(z.array(types.string())),
    email_preferences: types.optional(z.lazy(() =>
      EmailPreferences$inboundSchema
    )),
    account_id: types.optional(types.string()),
    two_factor: types.optional(types.boolean()),
    status: types.optional(types.string()),
    root: types.optional(types.boolean()),
    technical_role: types.optional(types.string()),
    group_count: types.optional(types.number()),
    sub_account_count: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "first_name": "firstName",
      "last_name": "lastName",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "last_login": "lastLogin",
      "all_sub_accounts": "allSubAccounts",
      "email_preferences": "emailPreferences",
      "account_id": "accountId",
      "two_factor": "twoFactor",
      "technical_role": "technicalRole",
      "group_count": "groupCount",
      "sub_account_count": "subAccountCount",
    });
  }),
);

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}
