/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";
import {
  SubAccountSummary,
  SubAccountSummary$inboundSchema,
} from "./subaccountsummary.js";

export type UserSubAccountsResponse = {
  /**
   * A list of product environments (sub-accounts) that the user has access to.
   */
  subAccounts?: Array<SubAccountSummary> | undefined;
};

/** @internal */
export const UserSubAccountsResponse$inboundSchema: z.ZodType<
  UserSubAccountsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  sub_accounts: z.array(SubAccountSummary$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "sub_accounts": "subAccounts",
  });
});

export function userSubAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<UserSubAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UserSubAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UserSubAccountsResponse' from JSON`,
  );
}
