/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { CedarError, CedarError$inboundSchema } from "./cedar-error.js";
import { SDKValidationError } from "./sdk-validation-error.js";

export type ValidateCedarPolicyResponse = {
  valid: boolean;
  errors?: Array<CedarError> | undefined;
};

/** @internal */
export const ValidateCedarPolicyResponse$inboundSchema: z.ZodMiniType<
  ValidateCedarPolicyResponse,
  unknown
> = z.object({
  valid: types.boolean(),
  errors: types.optional(z.array(CedarError$inboundSchema)),
});

export function validateCedarPolicyResponseFromJSON(
  jsonString: string,
): SafeParseResult<ValidateCedarPolicyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidateCedarPolicyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidateCedarPolicyResponse' from JSON`,
  );
}
