/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { CedarError, CedarError$inboundSchema } from "./cedarerror.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type ValidateCedarPolicyResponse = {
  valid: boolean;
  errors?: Array<CedarError> | undefined;
};

/** @internal */
export const ValidateCedarPolicyResponse$inboundSchema: z.ZodType<
  ValidateCedarPolicyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  valid: z.boolean(),
  errors: z.array(CedarError$inboundSchema).optional(),
});

export function validateCedarPolicyResponseFromJSON(
  jsonString: string,
): SafeParseResult<ValidateCedarPolicyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidateCedarPolicyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidateCedarPolicyResponse' from JSON`,
  );
}
